### ISSUE TITLE
Treat elements with contenteditable=plaintext-only as textareas

### ISSUE THREAD

**Issue by ghost** [1995eaton/chromium-vim#111]
When I try to enter some text in such fields(currently it is used in google+), cvim treats keyboard input as if there are no textarea. But the expected behaviour is to treat them like textareas, thus ignoring input sent to them.

How to reproduce:

Go to google+, try writing a comment or adding a new post.

Or just check this fiddle: http://jsfiddle.net/58ss8de2/ and try typing something in the contenteditable field

**Comment by daphen** [comment]
Is there a way to just highlight items? Like, put focus on them?
Not all input fields are highlightable with "f", I use several forums that don't let me focus on the input fields for writing comments and it's driving me nuts. (Actually this is the first site I've tried that it actually works on and I don't know why.)

Try head-fi for example, I can't highlight the response text field in private messages.
