### ISSUE TITLE
cVim not working with "non regular" web sites

### ISSUE THREAD

**Issue by xnaveira** [1995eaton/chromium-vim#118]
cVim seems not to be working at all when the tab you're on is a chrome app or a local file, is that a general problem with cVim or do I have to change some configuration?

**Comment by miraxxx** [comment]
@1995eaton any news on chrome://extensions urls?

I've been trying to update the manifest.json file - no luck.

**Comment by a13ph** [comment]
I think you have to specify each url in particular, so this would be painful for some. 
https://code.google.com/p/chromium/issues/detail?id=153245

**Comment by guoang** [comment]
> @baldrs is right, Google's security policies for Chromium are fairly limiting. You can make cVim run on local files (URLs with the `file://` protocol) by checking the `Allow access to file URLs` checkbox in `chrome://extensions`.
> 
> You can make cVim work on `chrome://*` URLs by navigating to `chrome://flags` and enabling the `extensions-on-chrome-urls` flag. You'll also have to add `chrome://*` to the [manifest.json](https://github.com/1995eaton/chromium-vim/blob/master/manifest.json#L92) file (the array at line 92). Keep in mind that enabling this flag is unsupported by Google, and it may pose a security risk.

not work

**Comment by joanmarcriera** [comment]
> > @baldrs is right, Google's security policies for Chromium are fairly limiting. You can make cVim run on local files (URLs with the `file://` protocol) by checking the `Allow access to file URLs` checkbox in `chrome://extensions`.
> > You can make cVim work on `chrome://*` URLs by navigating to `chrome://flags` and enabling the `extensions-on-chrome-urls` flag. You'll also have to add `chrome://*` to the [manifest.json](https://github.com/1995eaton/chromium-vim/blob/master/manifest.json#L92) file (the array at line 92). Keep in mind that enabling this flag is unsupported by Google, and it may pose a security risk.
> 
> not work

Not working for me as well.
