### ISSUE TITLE
toggleCvim does not seem to work

### ISSUE THREAD

**Issue by lervag** [1995eaton/chromium-vim#136]
First: Love your plugin!

So, I was trying to use the following options for gmail:

``` vimL
site 'https://mail.google.com/*' {
 call :pintab
 call toggleCvim
}
```

The idea was to first pin the gmail tab, then turn off `cvim` to use gmails keyboard shortcuts. This doesn't work for me on Chromebook and Arch Linux (on google-chrome-beta branch). Further, I I don't use the option above and just try to toggle with the default keybinding `<a-z>` (alt-z), nothing happens. Generally, I am not able to turn off cvim on gmail except by using the blacklist option.

**Comment by tristan957** [comment]
Is there any update on this? Vimperator is extremely nice in that Shift-Esc toggles Vimperator on and off
