### ISSUE TITLE
Possiblity to disable for x minutes

### ISSUE THREAD

**Issue by metude** [1995eaton/chromium-vim#140]
I use imagus with cvim. Imagus has a feature about image rotating by pressing r. Sometimes I need to rotate images. But same keystroke reloads page in cvim. So is it possible to add "disable cvim for X minutes" feature?

**Comment by srustamo** [comment]
> You can also disable cVim (and re-enable) with a keybinding (Toggle the enabled state of cVim)

I realize that this thread is quite old, but I can't find the toggle cVim command to bind to. What is the best way to disable cVim on a site with a shrotcut?

**Comment by ArtBIT** [comment]
I realize that this thread is quite old, but for anyone else looking for this, the shortcuts are now moved inside the burger menu in the top left of the chrome://extensions page.

![chrome-extensions-menu](https://user-images.githubusercontent.com/184220/67275422-dc65c280-f4c2-11e9-9296-386cb167d7e7.png)
![chrome-extensions-menu-expanded](https://user-images.githubusercontent.com/184220/67275428-e12a7680-f4c2-11e9-82ec-b8fdc77191b3.png)
