### ISSUE TITLE
]] doesn't work for me

### ISSUE THREAD

**Issue by in-out** [1995eaton/chromium-vim#184]
same as title
I have tested at google,v2ex...
regex?

**Comment by unc0** [comment]
@in-out After PR #196 , you can use this settings to support Chinese websites:

```viml
let nextmatchpattern = "((?!first|第一页|首页)(next|下一页|后一页|forward|前进|more|更多|>|›|»| )+)"
let previousmatchpattern = "((?!last|最后一页|尾页)(prev(ious)?|上一页|前一页|back|后退|less|更少|«|<|‹| )+)"
```

**Comment by 1995eaton** [comment]
This issue should be fixed as of now

**Comment by 097115** [comment]
Strangely it doesn't work for me [here](https://lj.rossia.org/users/tiphareth/friends?skip=25) or [here](https://chto-chitat.livejournal.com/?skip=50).

Here are my patterns:

    let nextmatchpattern = "((?!first)(Next|next|Следующие|forward|more|>>|>|›|»| )+)"
    let previousmatchpattern = "((?!last)(Previous|prev(ious)?|Предыдущие|back|less||«|<<|<|‹| )+)"
