### ISSUE TITLE
Doesn't work for file:// and about:blank

### ISSUE THREAD

**Issue by jjzz** [1995eaton/chromium-vim#205]
1. cvim doesn't accept any input for page "about:blank"
2. I have my own local index.html with hundreds of urls as homepage. But cvim doesn't work for URI like file://... 

BTW,
Is that possible to avoid 'f' or 'f*' hints after using 'f'/'F' to create link hints? I prefer the occasional sequence 'ff' to keep the initial staus (create link hints, and then cancel), instead of following a random url.

Thanx!
zz

**Comment by valir** [comment]
@jjzz: concerning item n° 2: it actually works, but you need to activate the "allow access to file URLs" on the exensions page for cVim. Already loaded file:// pages must be refreshed after checking the this option.

**Comment by 1995eaton** [comment]
@valir is right about your second point. The first one isn't possible due to limitations in Chromium. As a workaround, I have created an `about:blank` clone (type `:tabnew` in the command bar and press enter to see it).

For the last point, you could add this to the config area =>

```vim
let hintcharacters = 'asdgqwertzxcvb'
```

**Comment by stumash** [comment]
#78 might be of use to viewers of this page
