### ISSUE TITLE
semicolon does not work as linkhint

### ISSUE THREAD

**Issue by y2kbugger** [1995eaton/chromium-vim#209]
let hintcharacters = "qwertyuiopghzxcvbnm,.;[=-0987654321`"

I noticed that links that use semicolons dont respond.

ps. I have it set this way as to let my web browsing increase keyboarding skills

**Comment by 1995eaton** [comment]
Changing hint focus happens when a link hint obscures another hint. It brings the hidden hint to the front. The alt key also does this, so I've removed the semi-colon mapping like you asked.
