### ISSUE TITLE
cVim breaks bootstrap typeahead

### ISSUE THREAD

**Issue by rcoedo** [1995eaton/chromium-vim#210]
I'm getting wierd behaviour when typing into fields that use bootstrap typeahead plugin. It works fine when I disable cVim. I guess this is some sort of problem with the javascript code cvim inserts into the webpage.

You can try it here: http://getbootstrap.com/2.3.2/javascript.html#typeahead

**Comment by 1995eaton** [comment]
Should be fixed now

**Comment by rcoedo** [comment]
Great, thank you!
