### ISSUE TITLE
open in external editor when using createTabbedHint on an inputbox

### ISSUE THREAD

**Issue by y2kbugger** [1995eaton/chromium-vim#214]
I imagine this could be either really easy or really hard to implement.

**Comment by 1995eaton** [comment]
Just added the feature. See `createEditHint` in the help file.

**Comment by y2kbugger** [comment]
in the newest version, neither imap for external editor nor createEditHint open the external editor, but createEditHint does focus an input box and does only hint input boxes.
Not sure if it was done this way but i think in addition to createEditHint it should work like think

map f createLinkHint #follow link in same tab or focus input box
map F createTabbedLinkHint #follow link in new tab, or external edit input box
