### ISSUE TITLE
Support for reading config from dotfile.

### ISSUE THREAD

**Issue by marcusramberg** [1995eaton/chromium-vim#216]
I'm a huge fan of this plugin, but I find storing my config in a gist to be a big hassle when switching between machines. Would be awesome if it could read config from your $HOME as well, for instance ~/.cvimrc or something similar.

**Comment by martin-svk** [comment]
+1 I would love that too.

**Comment by 1995eaton** [comment]
Unfortunately, Google's JavaScript API for Chrome does not currently allow something like this. I'll keep an eye on it, but for now it's not possible as far as I can tell.
