### ISSUE TITLE
toggleBlacklisted doesn't work

### ISSUE THREAD

**Issue by mrkyle7** [1995eaton/chromium-vim#226]
Have tried:

unmap q
map q toggleBlacklisted

and

map <A-q> toggleBlacklisted

But nothing seems to work.

Chrome: Version 40.0.2214.93 m
CVim version:  1.2.66

**Comment by 1995eaton** [comment]
Strange, looks like I never added that command. I just added it now, but you'll need to set the binding via the chrome://extensions keyboard shortcuts section (so that the bindings will work even if cVim isn't running on the tab).

**Comment by mrkyle7** [comment]
this works great! Thanks
