### ISSUE TITLE
Unable to type on twitter,google plus and disqus with cVim

### ISSUE THREAD

**Issue by wicastchen** [1995eaton/chromium-vim#231]
I'm using [chrome-dev](https://aur.archlinux.org/packages/google-chrome-dev/) 42.0.2292.0 dev (64-bit).
There is no evident error shown in the console.I have tested typing with cVim disabled,it works fine.So I'm sure the problem is caused by cVim.

**Comment by 1995eaton** [comment]
ebf430a has fixed G+ and twitter as far as I can tell. I don't have a disqus account so if you could verify that it fixes typing on there that would be great. Thanks

**Comment by wicastchen** [comment]
Problem fixed.
