### ISSUE TITLE
The latest update on 2/06/2015 has conflict to Google Hangouts Plugin.

### ISSUE THREAD

**Issue by yingwuzhao** [1995eaton/chromium-vim#232]
The latest update on 2/06/2015 has conflict to Google Hangouts Plugin.

cVim prevent user from being able to typing into the Hangouts mail chat windows. I have to disable cVim for now!!

**Comment by 1995eaton** [comment]
I pushed an update to the store that should fix this [issue](https://github.com/1995eaton/chromium-vim/issues/231). Check to make sure you're running version 1.2.69 and see if the problem persists. I just checked Hangouts and it seems to be working for me.

**Comment by yingwuzhao** [comment]
Awesome, thanks a lot man :-)
