### ISSUE TITLE
pass hyperlink as argument to script

### ISSUE THREAD

**Issue by justmytwospence** [1995eaton/chromium-vim#233]
It would be a cool feature if you there was a way to create a key binding like `q` or `f`, but when you select a hyperlink, it passes that hyperlink through as an argument to a script.

**Comment by 1995eaton** [comment]
Is something like this what you had in mind (just added this in the above commit)?

```vim
" Script hints
echo(link) -> {{
  alert(link.href);
}}
map <C-f> createScriptHint(echo)
```

**Comment by justmytwospence** [comment]
exactly - awesome!
