### ISSUE TITLE
Default mappings for keys ':' and ';' broken

### ISSUE THREAD

**Issue by usommerl** [1995eaton/chromium-vim#234]
Pressing key `:` should execute the command `openCommandBar` and pressing key `;` should execute the command `setMark`. Instead of the expected result, these keyboard shortcuts move the current tab left or right. I'm experiencing this behaviour with a clean chromium profile (only cvim installed) and without any additional cvim settings (empty cvimrc). 

cVim: 1.2.69
Chromium: 40.0.2214.111
OS: Linux

**Comment by wrigleyster** [comment]
+1
Probably usommerl, same as myself, uses a non-US Keyboard where `;` and `:` are to the right of `M` (thus where `<` and `>` are located on an American keyboard)

My keyboard layout is 'dk', and thus I might add that pressing `Æ` which is placed where `:` is located on the American keyboard also does not execute `openCommandBar`

**Comment by valir** [comment]
On my french layout:
- pressing ":" triggers "/"
- pressing "/" triggers "?"
How can I upvote this issue as currently I can no longer use cVim!

**Comment by 1995eaton** [comment]
@valir, were these key bindings previously working for you?

**Comment by valir** [comment]
yes, they used to work very well before the last update.

**Comment by usommerl** [comment]
I'm using a german keyboard layout and the keybindings were previously working for me as well.

**Comment by azmd** [comment]
Same issue here on German keyboard layout. 
Interestingly, the issue only pops up under Linux - my Macbook Pro, also with German Layout, works like it used to before.

**Comment by 1995eaton** [comment]
@azmd, interesting indeed. I'm wondering if this might be something to do with an update in Chrome. If anyone could go back a few commits and check to see if this issue disappears we can confirm that it's an issue with cVim. I'd do it myself, but I'd have to find a way to toggle between German and American layouts to test the behavior.

**Comment by 1995eaton** [comment]
After trying out the German keyboard layout, I was able to get a fix that worked for me. Try 4eab005 and see how it works out.

**Comment by azmd** [comment]
Confirmed fixed on Chrome Version 40.0.2214.111 (64-bit), Linux, Germany Keyboard. Thanks Jake!

**Comment by usommerl** [comment]
Thanks a lot!

**Comment by 1995eaton** [comment]
Assuming this is fixed based on @azmd and @usommerl's replies. Will reopen if people still have the issue.
