### ISSUE TITLE
C-n does not work anymore

### ISSUE THREAD

**Issue by Linuus** [1995eaton/chromium-vim#235]
Hi!

Recently using C-n to select items in the command list opens a new window. It used to work, and yes I have set the option in chrome://extensions

Anyone else having this problem?

**Comment by usommerl** [comment]
I have the same problem. It used to work for me as well. If I press C-n now, cvim advances to the next item in the command list AND chromium opens a new window.

**Comment by 1995eaton** [comment]
Should be working now.
