### ISSUE TITLE
I have Caps Lock and Control swapped at OS level, however, cVim does not honour that

### ISSUE THREAD

**Issue by benwoodward** [1995eaton/chromium-vim#236]
![image](https://cloud.githubusercontent.com/assets/1472981/6122449/ae7ab1be-b147-11e4-9892-60f426b698f7.png)

My Caps Lock key functions as my Control key and vice versa, however, when I use cVim, Control key (which is my Caps Lock key) works as the control key, and Caps Lock doesn't do anything. This results in my Caps Lock being toggled.

Is there a way to change this with .cVimrc?

**Comment by 1995eaton** [comment]
What KeyCode is showing up on http://1995eaton.com/keydown/ when you press the control key? What about the caps lock key?

**Comment by benwoodward** [comment]
PRESSING .. oops, I mean, pressing the control key on my keyboard gives;

```
KeyCode: 20, Shift: false, Ctrl: false, Alt: false, Meta: false	<@20>
```

Pressing Caps Lock gives;

```
KeyCode: 17, Shift: false, Ctrl: true, Alt: false, Meta: false	<@17C>
```

**Comment by 1995eaton** [comment]
And these results occur when you have Caps Lock -> Ctrl and Ctrl -> Caps Lock mapped?

**Comment by benwoodward** [comment]
Correct. I have also verified that these mappings are working everywhere else outside of cVim.

**Comment by 1995eaton** [comment]
Strange, according to the data you've posted, the remap is working properly with the JavaScript event listeners (I'm getting the same results for caps lock and control). Are normal Chrome bindings like Ctrl+t working with the modifier keys being remapped?

**Comment by wooger** [comment]
Mac OS Chrome uses Cmd-t etc instead of control in almost every case, so
that may not be a good test.

-
e:oliver.agar@sharpblue.net
t:+447968965115

**Comment by benwoodward** [comment]
My cVimrc is empty

![image](https://cloud.githubusercontent.com/assets/1472981/6123663/782baef8-b159-11e4-9226-d4d56d8de98e.png)

I have tried disabling all Chrome extensions, which made no difference.

I have also tried restarting Chrome. No effect.

**Comment by 1995eaton** [comment]
Which cVim command are you trying to run that is bound to the Control key?

**Comment by benwoodward** [comment]
scrollPageDown

Damn, I just realised it's actually mapped to ```d``` not ```<C-d>```, so perhaps the problem is between the keyboard and the chair. I'm sorry if I've wasted your time.
