### ISSUE TITLE
Ability to whitelist

### ISSUE THREAD

**Issue by collinpeters** [1995eaton/chromium-vim#239]
I have a situation where I would like to use cVim at http://domain/foo/bar, but not at http://domain/foo. Is this possible at all? I was thinking a whitelist that overrode the blacklist.

**Comment by 1995eaton** [comment]
Just added this. Prefix blacklist items with `@` and they'll act as whitelists. Example:

```vim
let blacklists = ['@http://domain/foo/bar', 'http://domain/foo/*']
```

**Comment by collinpeters** [comment]
Awesome turnaround!

**Comment by collinpeters** [comment]
Any ETA on release of this?
