### ISSUE TITLE
Multi-word history search in :tabnew, :open, etc. only works for full words, in order in which they appear in page title

### ISSUE THREAD

**Issue by terminalmage** [1995eaton/chromium-vim#243]
Imagine a website with the page title "Lorem Ipsum Dolor". Currently, when you start typing the command `:tabnew lorem ipsum`, this site will show up in the search matches. However, `:tabnew ipsum lorem` or `:tabnew lor ip` will not. It would be a neat enhancement to support these two use cases.

**Comment by johnbeard** [comment]
This works for me on 1.2.74. For example, I can use `:tabnew BBC Home` and the first option I get is `Home - BBC News`.
