### ISSUE TITLE
External editor does not open

### ISSUE THREAD

**Issue by y2kbugger** [1995eaton/chromium-vim#245]
haven't been able to get it to open for a while. Finally upgraded to newest version of the server script and the extension and that didn't fix it.

neither method works:
imap <C-o> editWithVim
map a createEditHint

the Edithints are created, and the input gets focused, but external editor does not run.

The ports match.

**Comment by 1995eaton** [comment]
And the python script is running?

**Comment by y2kbugger** [comment]
yup

$ top -bn 1 | grep cvim_server.py
10427 y2k       20   0   82.1m  13.3m   0.0  0.2   0:00.54 S          `-
cvim_server.py


and attempting to run another instance correctly fails because the port is
taken. I've tried 8001, 9xxx, and 4xxx and all are the same result.

also token is being created:

$ ls -al | grep token
-rw-r--r--  1 y2k y2k    36 Feb 18 23:56 .cvim_server.token

**Comment by 1995eaton** [comment]
Is the python script spitting out any error messages?

**Comment by y2kbugger** [comment]
only if I try to open a second instance. One the main one no output
whatsoever

**Comment by y2kbugger** [comment]
the only modification to the code that I am running right now is to all
chrome://* in the manifest. Could that affect this?

**Comment by y2kbugger** [comment]
I add print statements to the POST handler and a GET handler and then try
to open external editor. Nothing was printed at all.

**Comment by 1995eaton** [comment]
If you're running on a port other than 8001, you have to set the `vimport` option to the correct port. I'd also try changing the `vimcommand` option (default value is `gvim -f`). Just to confirm, you're using the latest commit (cc00e0a)?

**Comment by y2kbugger** [comment]
had vimport and vimcommand customized before and it was working fine. In
the process of debugging, I let them both back to default.

yes that the commit i'm on. Technically I am one ahead of that for the
chromepages fix:

commit f47050db974f348a995503cc20b50fa832e63148
> Author: y2k <git@y2kbugger.com>
> Date:   Tue Jan 27 21:44:03 2015 -0500
>     Enable extensions to run on chrome:// pages
> commit cc00e0af03e95b20fd5f6be17c506755fc7a3926
> Author: 1995eaton <1995eaton@gmail.com>
> Date:   Wed Feb 18 11:41:24 2015 -0500
>     CSS tweaks

**Comment by 1995eaton** [comment]
Strange you're having this issue. You might want to check if cVim's background script is throwing any errors (`chrome://extensions` -> `inspect view: background page`).

**Comment by y2kbugger** [comment]
aha! it is looking for the token in the extension folder, whereas the
server makes in the same directory as the script, which the way I had it
were different.

actions.js:674 GET
chrome-extension://cknnkpgcpbjjahlobkffeifnadbehacn/.cvim_server.token
net::ERR_FILE_NOT_FOUND


here are some other misc errors I noticed and typed up before i saw the big
one:

they are in messenger.js
Error in event handler for (unknown): ReferenceError: Mappings is not
defined￼

>       break;
>     case 'sendSettings':
> >>>   Mappings.defaults = Object.clone(Mappings.defaultsClone);
>       if (!Command.initialLoadStarted) {
>         Command.configureSettings(response.settings);
>       } else {
>         Mappings.parseCustom(response.settings.MAPPINGS);
>         settings = response.settings;
>       }


Error in event handler for (unknown): ReferenceError: Command is not defined

>     case 'commandHistory':
>       for (key in response.history) {
> >>>        Command.history[key] = response.history[key];
>       }
>       break;


Error in event handler for (unknown): ReferenceError: Mappings is not
defined

>   switch (response.type) {
>     case 'hello':
>       PORT('getSettings');
>       PORT('getBookmarks');
>       PORT('getQuickMarks');
>       PORT('getSessionNames');
>       PORT('retrieveAllHistory');
>       PORT('sendLastSearch');
>       PORT('getTopSites');
>       PORT('getLastCommand');
>       break;
>     case 'updateLastCommand':
> >>>      Mappings.lastCommand = JSON.parse(response.data);
>       break;


Error in event handler for (unknown): ReferenceError: Search is not defined

>     case 'bookmarks':
>       Marks.parse(response.bookmarks);
>       break;
>     case 'topsites':
> >>>      Search.topSites = response.sites;
>       break;
>     case 'buffers':

**Comment by 1995eaton** [comment]
Awesome, so this fixes your problem? I'll have to look into the other errors (I've been getting similar messages since one of the recent updates).

**Comment by y2kbugger** [comment]
If I wasn't using the extension from github with the server included, does
cvim know where to look for the token? we are supposed to have to start the
server script by our own means right?

**Comment by y2kbugger** [comment]
Also I still get that error when attempting to open external editor when I
run the script from ~/bin or from the extension directory.

**Comment by y2kbugger** [comment]
I take that back, it is fixed if I run it from the git directory.

**Comment by 1995eaton** [comment]
Just pushed a commit that removes the need for the token file, so this shouldn't be a problem anymore. You should be able to run the server script from any directory.
