### ISSUE TITLE
[Feature Request] CTRL-N and CTRL-P to select item in :open

### ISSUE THREAD

**Issue by okuramasafumi** [1995eaton/chromium-vim#246]
I'd like to use `CTRL-N` and `CTRL-P` to select item from `:open` or `:tabnew` command, because we often use those keys in command line of vim.

**Comment by 1995eaton** [comment]
This is already a feature, see `cncpcompletion` in the [README.md](https://github.com/1995eaton/chromium-vim/blob/master/README.md).

**Comment by simonwjackson** [comment]
I have set all of the options but i cant get this to work
