### ISSUE TITLE
cvim stops working sporadicly

### ISSUE THREAD

**Issue by zeltak** [1995eaton/chromium-vim#25]
Hi

i cant quite put my finger on it but it seems that every X minutes/hours cvim stops working. all hotkeys, quickmakrs etc dont work until i restart chrome. any idea how one goes on debugging this? does anyone else have these issues

also is there a way in new chrome version to have cvim work in new tabs etc or will that never work?

best

Z

**Comment by DavidGretzschel** [comment]
I've noticed the same behaviour for as long as I've been using cVim. It's definitely "still a thing", I'm afraid. In the past, this made me curse the gods and just close and reopen Chrome at which point it usually worked again. I'll provide the logs as described here, soon.
