### ISSUE TITLE
a key to toggle/switch between 2 last tabs

### ISSUE THREAD

**Issue by zeltak** [1995eaton/chromium-vim#263]
Hi again

is there an option (and if not can i request one) to assign a key shortcut to toggle between the 2 last visited tabs (kinda like application alt-tab)
i used such a thing alot in pentadactyl/vimperator back in the day and miss it dearly :)

thx alot

z

**Comment by 1995eaton** [comment]
See the `lastUsedTab` command, (`<C-6>`).
