### ISSUE TITLE
goToTab doesn't do anything

### ISSUE THREAD

**Issue by Alok** [1995eaton/chromium-vim#264]
I tried using the goToTab command by pressing <N>% but it does nothing. The page I try it on doesn't appear to matter. It also failed after I disabled every other extension.

**Comment by 1995eaton** [comment]
Seems to work here. Are you using a non-American keyboard layout?

**Comment by Alok** [comment]
No, I'm on the 2013 Macbook pro with standard US keyboard.

**Comment by 1995eaton** [comment]
Strange, and just to confirm, you're pressing the number of the tab you want to go to and then hitting `%`? Also, does hitting `%` without pressing a number take you to the first tab in the current window?

**Comment by Alok** [comment]
Yep. Pressing just % does work the first time, but a number followed by it doesn't. And then it stops working altogether.

**Comment by roll** [comment]
<N>% works for me. But I can't to figure out how to use GoToTab in bindings. What the right syntax?

**Comment by 1995eaton** [comment]
Just found a bug that may cause this issue to occur. Let me know if the above commit fixes it, @Alok

**Comment by Alok** [comment]
The default mapping now works, but remapping it doesn't. So it looks like your commit worked for the most part.

**Comment by jshevek** [comment]
Should this issue be closed now?
