### ISSUE TITLE
Easier open link in new tab 

### ISSUE THREAD

**Issue by kidphys** [1995eaton/chromium-vim#265]
Right now cVim allows to open link in new tab by highlight link using 'f'. However I notice for me the decision to open the link new tab usually comes after the link is already highlighted. 

What if, for example we can "!az" instead of "az" would open link in new tab instead of current tab.

What do you guys think?

**Comment by 1995eaton** [comment]
If you hold the shift key while typing the last key for a hint, the link will open in a new tab regardless of whether `createHint` or `createTabbedHint` have been called. Is this what you are looking for?

**Comment by kidphys** [comment]
Cool, @1995eaton ! Didn't catch that in the doc.
