### ISSUE TITLE
d mapping persists despite being unmapped and remapped

### ISSUE THREAD

**Issue by Alok** [1995eaton/chromium-vim#273]
I remapped **d**  to move the tab right and I unmapped its default functionality to go a page down. However, it still goes down even as it moves the tab correctly, which is intensely annoying.

**Comment by 1995eaton** [comment]
What do you have in your cvimrc?

**Comment by Alok** [comment]
unmap d
map d moveTabRight

**Comment by Alok** [comment]
sorry clicked the wrong button and accidentally closed issue

**Comment by 1995eaton** [comment]
Seems to be working here. Is that all you have in your cVimrc or are there other lines in it? Also, what version of Chrome are you using and what OS are you running? Thanks

**Comment by Alok** [comment]
I'm running OSX 10.10.3 and Version 41.0.2272.118 (64-bit). There are other lines in my cvimrc. If you want the full thing, I can paste it, but it's pretty long.

**Comment by y2kbugger** [comment]
@Alok try it with only those lines in your cvimrc

**Comment by Alok** [comment]
It moves the tab right but moves the page down before doing so.
