### ISSUE TITLE
Can't remap <C-n>

### ISSUE THREAD

**Issue by achilleas-k** [1995eaton/chromium-vim#274]
This is my current cvimrc

```vim
let blacklists = ["http://localhost/*"]
let barposition = "bottom"
 
" mappings (attempting to match pentadactyl)
map u :undo<cr>
map s :open google<space> 
map S :tabnew google<space>
map d :quit<cr>
map <C-u> scrollPageUp
map <C-d> scrollPageDown
 
" tab switching
map <A-.> :tabnext<cr>
map <A-,> :tabprevious<cr>
map <C-n> :tabnext<cr>
map <C-p> :tabprevious<cr>
```

`<C-n>` does not remap to next tab no matter what I try. It always opens a new window. `<C-p>`, which by default is print page, works fine. #235 appears to be a similar issue, but it is marked as resolved.

I'm using the zip version of cVim, downloaded off github, with Chromium 41.0.2272.118 (64-bit).

**Comment by 1995eaton** [comment]
Mapping Chrome bindings (like `<C-n>`, `<C-w>`, etc) won't be possible until Chrome decides to add a keyboard listener for background scripts (see #275 for a similar issue). As a workaround, you can map `<C-n>` to `:tabnext<CR>` by going to `chrome://extensions`, clicking the `Keyboard shortcuts` link, and  mapping the row titled `Go to the next tab`.

**Comment by achilleas-k** [comment]
Excellent. Thanks.
