### ISSUE TITLE
Can't override default Chrome keyboard shortcuts

### ISSUE THREAD

**Issue by infokiller** [1995eaton/chromium-vim#275]
I'm not sure if Chrome allows an extension to override its keyboard bindings (like Ctrl+w that closes the current tab), so please let me know if it's not feasible.

Thanks!

**Comment by 1995eaton** [comment]
You can currently override some shortcuts via the `Keyboard shortcuts` section in the `chrome://extensions` page. However, this will be the only way shortcuts like this will work until/if Google decides to add a keyboard listener for background scripts.
