### ISSUE TITLE
Setting alt+k as keybinding for previousTab doesn't work well

### ISSUE THREAD

**Issue by infokiller** [1995eaton/chromium-vim#277]

**Comment by infokiller** [comment]
While it does move to the previous tab, it also passes the alt+k to Wikipedia which goes to the RecentChangesLinked of the current article.

**Comment by 1995eaton** [comment]
This is a Chromium [bug](https://code.google.com/p/chromium/issues/detail?id=433363&thanks=433363&ts=1415984108) that still hasn't been fixed (I submitted the issue last year and no one's gotten around to fixing it). As a temporary fix, I have gotten Wikipedia to ignore cVim bindings by adding this to my cVimrc:

```viml
site '*://*/*' {
  call :script [].slice.call(document.querySelectorAll('*[accesskey]')).forEach(function(e){e.removeAttribute('accesskey')});
}
```
