### ISSUE TITLE
Gmail file attachements button not responsive sometimes

### ISSUE THREAD

**Issue by infokiller** [1995eaton/chromium-vim#283]
I tested it in incognito with only cVim enabled. Sometimes after refreshing the email compose page, the attachment dialog opens for the first time, but closing it and clicking on the "add attachment" button again does nothing.

**Comment by y2kbugger** [comment]
I noticed this too, had no idea that it was caused by cvim, I figured it was to do with being on a weird linux DE.

**Comment by smartass101** [comment]
I can confirm this with with Chrome 46 an cVim 1.2.80

**Comment by einhander** [comment]
Same here. Chrome 46 c Vim 1.2.80. Debian.

**Comment by imiric** [comment]
Confirmed here as well. Disabling cVim makes the "Attach files" button work consistently.

Chrome 50.0.2661.75, cVim 1.2.83, Windows 10.
