### ISSUE TITLE
Don't open changelog on update

### ISSUE THREAD

**Issue by alexozer** [1995eaton/chromium-vim#290]
Do you think you could disable cvim from opening the changelog in a new tab every time it updates? I never know when it's going to do it, and I can't sleep at night knowing that anytime I'm looking at anything online I could suddenly have my focus ripped away. Just kidding, but thanks.

**Comment by 1995eaton** [comment]
Added as a feature. Add this to your rc: `set nochangelog`

**Comment by alexozer** [comment]
Sweet, thanks!
