### ISSUE TITLE
After closing a tab active left one

### ISSUE THREAD

**Issue by tkossak** [1995eaton/chromium-vim#291]
Is there a setting to make cVim activate a tab on the left of the one being closed (with ```x```)? Currently it activates the tab on the right.

**Comment by Fruglemonkey** [comment]
This can be done via a custom mapping.

map ^x closeTab
map x :exec ^xJ<CR>

**Comment by tkossak** [comment]
I modified it a bit:

    map ^x closeTab
    map x :exec ^xJ<CR>

and it works, thank you.
