### ISSUE TITLE
Enable to fuzzy-match links to follow

### ISSUE THREAD

**Issue by RobertAudi** [1995eaton/chromium-vim#30]
When you press `f/F` (by default) to follow a link, it displays letters that you need to press to follow one. It would be cool if it was possible to also type (part of) the text of a link to decide which one to follow. I imagine this would probably be a problem if the hints are letters (there would be conflicts), so I guess this feature should only work if the hints are numbers (i.e.: setting the `numerichints` setting).

**Comment by tobstarr** [comment]
@1995eaton is that what `typelinkhits` is used for? Is there an option to automatically open a link if there is only one more link matching?
