### ISSUE TITLE
mapping | can't do custom lines ending with trailing spaces

### ISSUE THREAD

**Issue by fohrums** [1995eaton/chromium-vim#302]
PROBLEM IN MY ~/.CVIMRC
=
```
" SETTING
set noautofocus
set nosmoothscroll
set autohidecursor
let searchlimit = 7
" QUICKMARK
let qmark g = ["https://mail.google.com/mail/u/0/#inbox"]
let qmark y = ["https://www.youtube.com/feed/subscriptions"]
" SEARCH
map <C-g>y :open duckduckgo !yt
map <C-g>Y :tabopen!  duckduckgo !yt
map <C-g>i :open duckduckgo !gi
map <C-g>I :tabopen duckduckgo !gi
```

Now, notice at the section titled <i> SEARCH</i>, because there I have custom search engines that are being re-directed by ddg and the problem with this is that if I do a key like `<C-g>y` to open a YouTube search engine it doesn't have an extra space at the end so that means i have to literally do the following:

```
<C-g>y, then manually typing space
```

EXAMPLE
=
<b>Limited to</b>:
```
<C-g>y
:open duckduckgo !yt
```
<b>Prefer</b>:
```
<C-g>y
:open duckduckgo !yt<SPACE>
```
which isn't ideal so my question is <b>how do I have leading intentional space characters at the end of a mapped line to a custom key</b>?

**Comment by johnbeard** [comment]
Why is `map <C-g>y :open duckduckgo !yt<SPACE>` not ideal? It seems to work for me - `<C-g>y`, then I can directly type the query and press enter, and it will send `!yt query` to DDG.

**Comment by 1995eaton** [comment]
@johnbeard is right. `<Space>` is used to indicate trailing spaces for commands
