### ISSUE TITLE
Emulate right click

### ISSUE THREAD

**Issue by rosshadden** [1995eaton/chromium-vim#305]
Right now we can "click" links and also "middle click" them by opening them in a new tab.  I think it would be useful to be able to "right click" them as well.  Once the context menu pops up, we can just use the arrow keys to navigate it, per Chromium's native bindings.

The use case I hit just now was I wanted to copy the URL of a link, and as it was a link to a zip file it wasn't as easy as `f<link keys>yyH`, which would go to the link, copy the URL, and then go back to the previous page.  I can see it also being useful to inspect the element, or open it in a new or incognito window.

**Comment by madiele** [comment]
I don't think right clicking can be done from a chrome extension, though you can actually copy a link on a page pretty easily by doing `gy`, I personally remapped it to `yf` which I find more logical, check the "Link Hints" section of the readme for similar commands

**Comment by rosshadden** [comment]
Oh cool, thanks!  I agree with `yf` and am going to remap that too.  It seems more vim-like to use `y<motion>`.
