### ISSUE TITLE
Where to store .cvimrc ?

### ISSUE THREAD

**Issue by collegeimprovements** [1995eaton/chromium-vim#306]
Hi, noob here
Where can I store .cvimrc file so all its mappings actually can be used?
I'm currently trying cvimrc section of the extension, but it doesn't seem to work for me. 

e.g. If I want to achieve <leader>g to open google in a new tab, How can I achieve this?

**Comment by adamdicarlo** [comment]
Allow the extension access to the local filesystem (in Chrome's extensions page), store your cvimrc whereever you want (such as `~/.cvimrc`), make sure it includes:

```
let configpath = '/path/to/.cvimrc'
set localconfig
```
then, iirc, run `:source /path/to/.cvimrc` from within the browser once and from now on it will just work. (Seems like you have to visit `:settings` to get changes to .cvimrc recognized.)

**Comment by 257** [comment]
horrible design... chicken-and-egg and self-inflicted...
fyi sourcing cvimrc doesn't work here.

**Comment by jessemillar** [comment]
@257 Not sure if this is new, but `:source` without options seems to reload the local `.cvimrc`.
