### ISSUE TITLE
confusion over quickmarks

### ISSUE THREAD

**Issue by zeltak** [1995eaton/chromium-vim#31]
Hi again

im a little confused on what im doing wrong with qmarks
i have tried these 3 types in my config:

let qmark a = ["http://www.reddit.com", "http://www.google.com", "http://twitter.com"]  
let qmark w = ["http://www.cnn.com"]
let qmark e = "http://www.espn.com"

yet none seem to work using gna/gnw/gne it always gives me an: Error: mark not set

what am i missing here

best

Z

**Comment by anoda9** [comment]
Using 1.2.79, this still seems to be an issue. 
let qmark r = "www.reddit.com" 
gnr --> qmark not found

**Comment by larryhynes** [comment]
This still seems to be an issue, at least with cvim installed from chrome store; manual install of unpacked extension makes `let qmark f = "foo"` work again.
