### ISSUE TITLE
Add themoviedb and thetvdb

### ISSUE THREAD

**Issue by devhell** [1995eaton/chromium-vim#315]
Hi,

Any chance of adding [themoviedb](https://www.themoviedb.org/) and [thetvdb](http://www.thetvdb.com/) to cvim?

Thanks!

**Comment by 1995eaton** [comment]
It looks like thetvdb doesn't have use completion engine, so you can just add a custom search engine like this:

```vim
let searchengine thetvdb = 'http://www.thetvdb.com/?string=%s&searchseriesid=&tab=listseries&function=Search'
```

I'll look into adding themoviedb into the search engines with autocomplete.

**Comment by devhell** [comment]
@1995eaton Ah, sorry about thetvdb, didn't see that. Thanks for the update, and thanks for looking into themoviedb. ;-)

**Comment by 1995eaton** [comment]
Just added themoviedb to the completion engines in 8ed9623. See the CHANGELOG for how to use it.

**Comment by devhell** [comment]
Wow, that was fast. Many thanks!!
