### ISSUE TITLE
Request:  Ability to disable address bar?

### ISSUE THREAD

**Issue by svermeulen** [1995eaton/chromium-vim#32]
One thing I really liked about some of the firefox vim-plugins is that you can disable the address bar.  The biggest source of frustration I find is that I sometimes get 'trapped' in the address bar and do not have access to cVim commands.  cVim has a command for open so the address bar seems redundant.  Is there a way to disable it?

**Comment by githorse** [comment]
Just want to upvote this feature request, should it ever become possible in Chrome (or Chromium?). The extra screen real estate and minimalist interface is one of my favorite things about Pendactyl/Vimperator -- I really miss this in Chrome.
