### ISSUE TITLE
Possible to switch to tab N by just pressing N?

### ISSUE THREAD

**Issue by endrebak** [1995eaton/chromium-vim#321]
I want to quickly change tabs by just pressing the number of the tab I want to go to. Is this possible? If so, I haven't been able to work out how... I know this won't work if you use other commands starting with numbers or have more than 9 tabs, but I never do.

(Thanks for cvim by the way, I have been playing around with all day and am impressed. Finally a vimlike browser complete enough to switch from Firefox).

**Comment by 1995eaton** [comment]
Pressing numbers repeats commands `<N>` times by default. You can change this behavior by mapping each number individually to a custom function to switch to tab `<N>`. Example:

'''vim
switchTab(n) -> {{ RUNTIME('goToTab', {index: n - 1}); }}
map 1 :call switchTab(1)<CR>
map 2 :call switchTab(2)<CR>
map 3 :call switchTab(3)<CR>
map 4 :call switchTab(4)<CR>
map 5 :call switchTab(5)<CR>
map 6 :call switchTab(6)<CR>
map 7 :call switchTab(7)<CR>
map 8 :call switchTab(8)<CR>
map 9 :call switchTab(9)<CR>
'''
