### ISSUE TITLE
Possible to search links only?

### ISSUE THREAD

**Issue by aalvarado** [1995eaton/chromium-vim#323]
In firefox you can hit ' and search links only, I don't know if there's something like that already in Cvim or not, and if not, would it be possible to add it?

Thanks for this great plugin!

**Comment by 1995eaton** [comment]
Works now with the mapping `openLinkSearchBar`. Alternatively, you can open a normal search bar (`/`) and type `?`. Example config:

```vim
map ' createLinkSearchBar
```

**Comment by aalvarado** [comment]
awesome, thanks @1995eaton
