### ISSUE TITLE
what's the default path to config file?

### ISSUE THREAD

**Issue by 257** [1995eaton/chromium-vim#325]
i see configpath but not clear which is read absence of one set by user. that is, where is the _shipped_ cvimrc?

**Comment by 1995eaton** [comment]
`configpath` isn't set by default. You'll have to set it yourself. Example:

```vim
let configpath = '/home/jake/.cvimrc' " You'll need to create this file.
set localconfig
```

**Comment by 257** [comment]
ok. where do i set that? i mean where is the main config file? it looks like a chicken and egg problem.

**Comment by 257** [comment]
and could you post your .cvimrc file please?

**Comment by 1995eaton** [comment]
The config is found in `chrome://extensions`. Here's mine for reference:

```vim
let configpath = '/home/jake/.cvimrc'
let homedirectory = '/home/jake'
set localconfig

let vimcommand = 'urxvt -e vim'
imap <C-o> editWithVim

set nosmoothscroll
set noautofocus
set cncpcompletion
set nohud
set nodimhintcharacters
set typelinkhints
let mapleader = ','
let zoomfactor = 0.05
let scrollduration = 250
let searchlimit = 25
let completionengines = ['google', 'wikipedia', 'imdb',
      \ 'amazon', 'wolframalpha', 'duckduckgo']
let qmark a = [ 'http://www.reddit.com/r/learnjavascript/new',
      \ 'http://www.reddit.com/r/learnpython/new/',
      \ 'http://www.reddit.com/r/learnprogramming/new']
let searchalias i = 'imdb'
map af createActiveTabbedHint
map $ lastTab
map 0 firstTab
map <Space> l
map <S-Space> h
map gS :viewsource&<CR>
map xx closeTab
map qq xx
map Q closeTab
map gs fullImageHint
map gq :restore<Space>
map a<Space> z<Enter>
map <C-e> z<Enter>
map <C-k> nextTab
map <C-j> previousTab
map cn :execute nzz<CR>
map cN :execute Nzz<CR>
map <C-d> :file ~/
map m* setMark
map <C-s> openLastHint
map <C-g> :set smoothscroll!<CR>
map <C-h> :nohl<CR>
map cc :set hud!<CR>
map aa :tabopen g<Space>
map ga :settings<CR>
map g0 scrollToLeft
map I yankHighlight
map g$ scrollToRight
imap <C-y> selectAll
imap <C-a> <C-i>
imap <C-l> forwardWord
imap <C-h> backwardWord
map <BS> <Nop>
map <Leader>s :source<CR>
map <Leader>n :set numerichints!<CR>
map ci :call getIP<CR>
map ? openLinkSearchBar

fixChromiumWikiBug -> {{
  [].slice.call(document.querySelectorAll('*[accesskey]')).forEach(function(e) {
    e.removeAttribute('accesskey');
  });
}}
site '*://*/*' {
  call fixChromiumWikiBug
}

getIP -> {{
  httpRequest({url: 'http://www.telize.com/geoip', json: true}, function(res) {
    Status.setMessage(res.ip + ' - ' + res.isp);
  });
}}

site '*://*.netflix.com/watch*' {
  unmap <Space>
  unmap f
}
```

**Comment by 257** [comment]
hmm, why are defining configpath at the top if this indeed you .cvimrc file? it's self-referencing itself?

in chrome://extensions i only see 'Options' is that what you meant?
 if i click on 'options' it opens a page with a css file at the bottom and cvimrc above it with a question mark in front of cvimrc! i don't know what to make of this page. am i supposed to set the path to my cvimrc there?

i'm loading cvimrc from git source tree so i would be easier if you could give me the path to cvimrc in the source tree. also it's easier to edit with vi as opposed to editing in the browser.

thanks

**Comment by ljohnston** [comment]
+1

No idea how this is supposed to work.

**Comment by 257** [comment]
and now i don't even see the 'Options' in chrome://extensions
1.2.84 or master
50.0.2661.102 (Official Build) (64-bit)

**Comment by 257** [comment]
@ljohnston it seems to me that localconfig can be *appended* to chrome://extensions config. lack of default path for to check for a local config file is rather bezzar, me thinks.

**Comment by whitelynx** [comment]
I'm using version 1.2.85. If you click the cVim icon in your toolbar (or menu, if you've hidden it from the toolbar) and select "Settings", it will take you to the options for cVim, which has a "cVimrc" section. Clicking "Options" under "cVim" in `chrome://extensions` will take you to the same options page.

**Comment by 257** [comment]
for me this is the url:
[chrome-extension://iolmdkeoknnbjobhaemaphlcfckeolop/pages/options.html](chrome-extension://iolmdkeoknnbjobhaemaphlcfckeolop/pages/options.html)

there should be a short-url/alias for this, imo.

**Comment by jorvi** [comment]
@1995eaton pathing is currently broken.

`/Users/myname/.cvim`, `~/.cvim`, $HOME/.cvim and all of those prefixed with `file:///` don't work.. latest macOS, latest Chrome, latest cVim.

**Comment by tjharman** [comment]
I just installed cvim and I agree, the doco about how this is supposed to work is very confusing.  I know it's free etc, but maybe a link to this github issue or something similar like a "Getting started" guide would help newbies like me. Thanks!

**Comment by 257** [comment]
moved to https://github.com/1995eaton/chromium-vim/issues/671
