### ISSUE TITLE
Feature request: Pin tabs from cvim

### ISSUE THREAD

**Issue by matthiasbeyer** [1995eaton/chromium-vim#327]
Hi,

I'd really like to be able to pin tabs from within cvim. I couldn't find such a command yet, though. Maybe I just missed it? If not, I request this feature!

**Comment by CodyReichert** [comment]
This is available already as a command - `:pintab`
See more here: https://github.com/1995eaton/chromium-vim#command-mode

**Comment by matthiasbeyer** [comment]
I'm sorry. Thank you for your reply!
