### ISSUE TITLE
Trying to remap "n" to "n zz"

### ISSUE THREAD

**Issue by anoda9** [1995eaton/chromium-vim#336]
I want cvim to automatically center the page after finding the next search result. Neither of these work:
>map n n\<Space\>zz
>map n nextSearchResult\<Space\>zz

What am I doing wrong?

**Comment by 1995eaton** [comment]
Currently, you have to map another key to `n` using the actual command name (e.g. `nextSearchResult`). Then map `n` to `:execute <OTHER KEY>zz<CR>`. For example:

```vim
map #n nextSearchResult
map n :execute #nzz<CR>
```
