### ISSUE TITLE
Site-specific commands run on focused tab rather than tab where event happens

### ISSUE THREAD

**Issue by jamessan** [1995eaton/chromium-vim#353]
I setup a command for Pandora to automatically pin its tab:

    site '*://*pandora.com/*' {
       call :pintab
    }

However, Pandora periodically loads new content and if that happens while another tab is focused, then that tab will be pinned.

**Comment by 1995eaton** [comment]
This should fix it. Let me know if it works for you now.

**Comment by jamessan** [comment]
That's working much better.  Thanks!
