### ISSUE TITLE
G doesn't go to bottom on the page for at least one site.

### ISSUE THREAD

**Issue by RatanRSur** [1995eaton/chromium-vim#355]
Hi, this is the only page for which I've found this problem but `G` instead takes me to the top of the page exactly like `gg`. `G` works fine elsewhere as far as I can tell.

http://community.topcoder.com/stat?c=problem_statement&pm=12514

**Comment by 1995eaton** [comment]
Seems to be working for me. What OS/Chrome version are you using and are you using the GitHub version of cVim or the Chrome Store version?

**Comment by RatanRSur** [comment]
OS X Yosemite and the Chrome store version.

**Comment by 1995eaton** [comment]
I can confirm this issue in the Chrome store version. It seems that I fixed it when I re-implemented some of the scrolling code in 1a330c2, however. I'll probably push a new version of cVim within a week, so that should fix this issue.

**Comment by RatanRSur** [comment]
Sounds good!

Love cVim btw, keep it up

**Comment by RatanRSur** [comment]
Fixed!
