### ISSUE TITLE
enable user to define new search engine(s)

### ISSUE THREAD

**Issue by 257** [1995eaton/chromium-vim#356]
this has already been implemented in dwb (gs) and possible in vimperator, pentadactyl et al. 'gs' in dwb for example picks up the "search" field in the current page and then ask for shortcut to be assigned to that engine.

**Comment by Tanath** [comment]
This is frustrating me. [Here's my cVimrc](https://gist.github.com/Tanath/46d32ae096cc6a9566cef7ffbf945830). I want to define a custom Google URL for my searches, defined/aliased as `g`, and set to default. None of these three things work right though. I can set the URL to default but it inserts `%s` at the front of the search (like `%stest`) whether I include it or not. Or it just uses the built-in `google` search anyway despite having searched with `g`.

**Comment by 257** [comment]
moved to https://github.com/brookhong/Surfingkeys

**Comment by Tanath** [comment]
Can you explain this? Is cVim being abandoned?
