### ISSUE TITLE
Doesn't work on https://chrome.google.com/webstore/category/apps

### ISSUE THREAD

**Issue by festerman** [1995eaton/chromium-vim#360]
... at all, as far as I can determine: the icon is greyed out. So it seems like it's by design. Maybe it's spillover from "blacklisting" chrome:// urls?

**Comment by 1995eaton** [comment]
Google doesn't let extensions run on the web store. There currently isn't any way to work around this (unlike the Chrome flag that can allow extensions to run on `chrome://*` URLs if enabled). I'll reopen the issue if anyone can think of a way to get around this.
