### ISSUE TITLE
Ctrl+F is suppressed on devdocs.io

### ISSUE THREAD

**Issue by Pastafarianist** [1995eaton/chromium-vim#361]
Steps to reproduce:

1. With cVim enabled, go to https://devdocs.io
2. Type anything in the search bar (it is active by default)
3. Hit `Ctrl+F`
4. The Chrome search window doesn't appear.

Then "disable cVim on this domain" and repeat. The problem is solved.

**Comment by Pastafarianist** [comment]
The problem also manifests at http://leconjugueur.lefigaro.fr. It focuses automatically on the search field, and hitting `Ctrl+F` doesn't reveal the search box.

**Comment by 1995eaton** [comment]
`<C-f>` is an input mapping. You can fix this by adding `iunmap <C-f>` to your config
