### ISSUE TITLE
Bind keys to other literal keys

### ISSUE THREAD

**Issue by infokiller** [1995eaton/chromium-vim#370]
Some websites (like Google Drive) has built in keyboard shortcuts that can't be customized. cVim could be used to customize these bindings if there's an option to map an arbitrary key sequence to another arbitrary key sequence. I'm thinking of something like `map x "y"` with the result that when I press x the page receives a key press of y.

Can this be done? and if not, will it be possible to implement this feature?

**Comment by 1995eaton** [comment]
Unfortunately not due to a long-standing Webkit bug. Until that's resolved (or Google decides to add an API which can do this), it can't be done.

**Comment by infokiller** [comment]
Thanks a lot for your response!

**Comment by MegaGM** [comment]
I'm sorry @1995eaton is it possible to bind Ctrl+j when in insert mode, to literal Enter key?
Somehow like that (doesn't work)
```
iunmap <C-j>
imap <C-j> <Enter>
```
