### ISSUE TITLE
I find a issue when I user "f" 

### ISSUE THREAD

**Issue by notejs** [1995eaton/chromium-vim#374]
1. Please open http://www.baidu.com 
2. Type some characters, you can see a search result list. 
3. Make all input blur via press "Esc"
4. Press 'f' trigger cVim mark all link and input box. You can see all mark characters float left. Below is a screenshot . 
![1](https://cloud.githubusercontent.com/assets/2126551/10780597/1a5cabea-7d7a-11e5-8085-e0c1e1efb7eb.jpg)

Once refresh current tab, it is works well, like below screenshot
![2](https://cloud.githubusercontent.com/assets/2126551/10780598/1a60b00a-7d7a-11e5-8f31-11f8ce24144e.jpg)

When I type some character again, this issue reproduce again.

**Comment by 1995eaton** [comment]
Should be fixed in 5150d44
