### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by xavierartot** [1995eaton/chromium-vim#380]
Hi,
How can I faster hjkl, right now is very slow and I use already Karabiner?
Thank you

**Comment by s-mage** [comment]
`set scrollstep=100` I guess. Or maybe more.

**Comment by 1995eaton** [comment]
If you want to turn smooth scrolling off, you can do:
```vim
set nosmoothscroll
```
If you want to adjust the time it takes for the scrolling to complete:
```vim
let scrollduration = 250 " Time in milliseconds
```

**Comment by xavierartot** [comment]
I used Karabiner, and is fast every where too.
