### ISSUE TITLE
open in new incognito tab?

### ISSUE THREAD

**Issue by koro-xx** [1995eaton/chromium-vim#388]
Thanks for this extension; it's incredibly useful. I have a feature request: would it be possible to add a "open link in new incognito tab" option?

**Comment by 1995eaton** [comment]
Using the latest commit, you can add this to your cvimrc to open a link in an incognito window:

```vim
incognitoHint(link) -> {{
    RUNTIME('openLinkWindow', {url: link.href, incognito: true});
}}
map <C-f> createScriptHint(incognitoHint)
```

Is this what you had in mind?

**Comment by koro-xx** [comment]
That was fast! I haven't tested it yet, but it looks right. Thanks a lot.
