### ISSUE TITLE
Configpath option does not support tilde

### ISSUE THREAD

**Issue by jgkamat** [1995eaton/chromium-vim#398]
It would be really nice if configpath would support tilde to denote home (if this is possible). For example:

`let configpath='~/.cvimrc'`
instead of 
`let configpath='/home/jay/.cvimrc'`

The latter is dependent on the username, which prevents the cvimrc configs from being portable...

**Comment by 1995eaton** [comment]
There isn't any way for me to assume the user's home directory. However, you can set it in a variable so that things like `let configpath='~/.cvimrc'` and `:file ~/` work normally:

```vim
let homedirectory = '/home/jay'
let configpath = '~/.cvimrc'
```
