### ISSUE TITLE
Ctrl+F ceases to work when a text field is activated

### ISSUE THREAD

**Issue by Pastafarianist** [1995eaton/chromium-vim#401]
Steps to reproduce:

1. With cVim enabled, go to http://www.wordreference.com/.
2. The search field is active by default. Press `Ctrl+F`. Nothing happens.
3. Disable cVim on "this domain" and reload the page.
4. The search field is again active, but now `Ctrl+F` works.

**Comment by 1995eaton** [comment]
`<C-f>` is one of the insert mappings (moves the cursor forward one character). You can disable it by adding `iunmap <C-f>` to your config. Let me know if this works or you meant something else.

**Comment by Pastafarianist** [comment]
It works, thank you.
This mapping should probably not be default. This behavior has been confusing me for a while.
