### ISSUE TITLE
Need some noob help

### ISSUE THREAD

**Issue by jaimehrubiks** [1995eaton/chromium-vim#402]
Hi, I've been using this extension for a long time but I can't find a way to see hidden tags when I use "f" to find a link.
I mean, when there are two tags very close to each other one will be on top of it, so how do I see the name of the one behind?

Thank you

**Comment by 1995eaton** [comment]
You can tap the alt key to switch the link hint focus.

**Comment by jaimehrubiks** [comment]
Can't believe I didn't see it. Thank you!

**Comment by Ape** [comment]
Useful. This should be documented somewhere.
