### ISSUE TITLE
defualt searchengine fails

### ISSUE THREAD

**Issue by 257** [1995eaton/chromium-vim#404]
on master branch, i'm getting this line hl'ed in red in Error section:

return (Complete[settings.defaultengine].requestUrl ||

let me know if you need more info.

**Comment by 1995eaton** [comment]
Should be fixed now

**Comment by 257** [comment]
now i get this:
 var defaultEngine = Complete.getEngine(settings.defaultengine);

**Comment by cjk** [comment]
The last commit fixes it for me, thanks!

**Comment by 257** [comment]
oh, now these two engines fail:
let searchengine gl = "https://www.google.co.uk/search?aq=t&btnI=I%27m+Feeling+Lucky&q=%s"
let searchengine t = "https://translate.google.co.uk/#fr/en/"

**Comment by 1995eaton** [comment]
This commit should fix it

**Comment by 257** [comment]
fixed here, thanks.
