### ISSUE TITLE
How to create a new empty window?

### ISSUE THREAD

**Issue by svermeulen** [1995eaton/chromium-vim#406]
I have a key mapped to `:tabnew` which works great and opens a new blank tab.  However, I can't seem to get the same working with a new window.  Executing `:new` doesn't do anything.

I also tried mapping a key to `:tabnew<cr>:tabdetach<cr>` but that didn't work either.

**Comment by 1995eaton** [comment]
Should be fixed

**Comment by svermeulen** [comment]
Works like a charm. Thanks for the incredibly fast fix  :D
