### ISSUE TITLE
youtube won't do completionengines

### ISSUE THREAD

**Issue by 257** [1995eaton/chromium-vim#408]
here is my setup:
```
let searchengine u   = 'http://www.youtube.co.uk/results?search_query=%s'
let completionengines = ['google', 'wikipedia',
      \ 'amazon', 'd', 'dd', 't', 'u' ]
```

**Comment by 1995eaton** [comment]
There are no completions for custom search engines. If you want uk YouTube results, you can do this:
```vim
let locale = 'uk'
let completionengines = ['google', 'wikipedia', 'amazon', 'youtube', 'd', 'dd', 't']
let searchalias u = 'youtube'
```

**Comment by dosentmatter** [comment]
@1995eaton 
If there are no completions for custom search engines, how come [in the docs](https://github.com/1995eaton/chromium-vim/blame/master/README.md#L98,L109), you add the `searchengine`, `dogpile`, into the `completionengines` array?

It doesn't break anything, but it also doesn't make completion work for `dogpile.com`. The [docs](https://github.com/1995eaton/chromium-vim/blame/master/README.md#L300-L308) say that only the following are allowed in `completionengines`:
```
['google', 'wikipedia', 'youtube', 'imdb', 'amazon', 'google-maps', 'wolframalpha', 'google-image', 'ebay', 'webster', 'wictionary', 'urbandictionary', 'duckduckgo', 'answers', 'google-trends', 'google-finance', 'yahoo', 'bing', 'themoviedb']
```
However, completion for `google-image` and `google-maps`don't work for me. Did those just break?
Also, does adding `dogpile` to `completionengines` do nothing?
