### ISSUE TITLE
Navigating 'issues' in chromiums default pdf-viewer

### ISSUE THREAD

**Issue by blueburningcoder** [1995eaton/chromium-vim#409]

**Comment by 1995eaton** [comment]
Chrome's built-in PDF viewer uses an embedded HTML object to display PDF files. As of now, there's no way to interact with it, which means no scrolling.

**Comment by defendrok** [comment]
Cannot navigation mapped keys be binded to arrow or Page up/down keys or simulate these key presses?

**Comment by 1995eaton** [comment]
No, Google only allows page scrolling via JavaScript (which can't interact with `object` elements). Chrome's extension API is too limiting.
