### ISSUE TITLE
Smooth scrolling stopped working

### ISSUE THREAD

**Issue by mrzool** [1995eaton/chromium-vim#410]
Smooth scrolling stopped working for me a couple of days ago.

Running Chrome 48.0.2564.109 on Mac OS X.

Anyone with the same problem?

**Comment by 1995eaton** [comment]
Smooth scrolling is now disabled by default in 1.2.81. See `:changelog` for how to re-enable it.

**Comment by mrzool** [comment]
Cool, thanks.
