### ISSUE TITLE
Doing a search hangs on large lists

### ISSUE THREAD

**Issue by ksalman** [1995eaton/chromium-vim#411]
Take for example this page http://winhelp2002.mvps.org/hosts.txt. If I try a search ```/10.```, it hangs. Sometimes I even see the chrome error 

Aw, Snap!
Something went wrong while displaying this webpage.

**Comment by 1995eaton** [comment]
This is a limit to how fast JavaScript can run. If you try using Chrome's `Ctrl+f` to search for `10`, it's not much faster (even with the fact that Chrome's `Ctrl+f` search is using compiled C++ code to search). I've tried many things to get cVim's search feature to perform better, without much luck.

**Comment by ksalman** [comment]
Oh I see, okay.
