### ISSUE TITLE
bookmarks in new window

### ISSUE THREAD

**Issue by rachaelbe** [1995eaton/chromium-vim#417]
there seems to be no way to open bookmarks in a new window? only the same tab, or new tab :(

**Comment by 1995eaton** [comment]
Just added this feature. Use it like this: `:bookmarks$ mybookmark`

**Comment by 257** [comment]
``$'' works for :chrome too, i wonder if we could open chrome pages in a new tab. or better yet, make that default. i.e. :chrome foo would open chrome://foo in a new tab by default, not the same page.
