### ISSUE TITLE
Mapping backspace key

### ISSUE THREAD

**Issue by kosl90** [1995eaton/chromium-vim#423]
Is there a way to map backspace key(I don't like the back behavior on windows)? If it is, please let me known, I don't find it, or can you make it?

Thanks.

**Comment by 1995eaton** [comment]
You can map it with `<BS>`. For example, I have it disabled in my config (I don't like the default behavior either): `map <BS> <NOP>`.

**Comment by kosl90** [comment]
Thanks

**Comment by kosl90** [comment]
@1995eaton map <BS> <NOP> seems not to work for 1.2.85

x64 windows 7, chrome 51.0.2704.84 m (64-bit)

**Comment by 1995eaton** [comment]
@kosl90 All mappings or just some?

**Comment by kosl90** [comment]
just <BS> failed for me.
