### ISSUE TITLE
Prepend a number to the command to repeat that command N times?

### ISSUE THREAD

**Issue by tsaber** [1995eaton/chromium-vim#426]
> Prepend a number to the command to repeat that command N times

I tried this as map j 5scrollDown but that doesn't work. Please explain.

**Comment by etmoore** [comment]
j is already mapped to ScrollDown.  If you press `5j`, it will perform the ScrollDown command 5 times. To change how many pixels the ScrollDown command covers, use the scrollstep setting.

**Comment by daGrevis** [comment]
How can I call `scrollDown` many times from mapping?

**Comment by 1995eaton** [comment]
Mappings such as `map j 5scrollDown` are now possible in the latest commit

**Comment by daGrevis** [comment]
Thanks, this is great!
