### ISSUE TITLE
Image download

### ISSUE THREAD

**Issue by paradox460** [1995eaton/chromium-vim#428]
We already have bindings for reverse image search, would it be possible to extend them to add Open image in new tab and possibly even save image?

**Comment by 1995eaton** [comment]
You can open images in a new tab with the `fullImageHint` mapping (I forgot to add the feature to the documentation, but it should be there after the latest commit). For example, I use this in my config: `map gs fullImageHint`. Downloading images is not possible using Chrome's current API features.

**Comment by paradox460** [comment]
That works, I can mix that and the copy-all-tabs-to-clipboard url, and then use hammerspoon to do the download.

Thanks!
