### ISSUE TITLE
Global zoom

### ISSUE THREAD

**Issue by Ape** [1995eaton/chromium-vim#431]
Currently cVim can zoom web pages. The zoom only affects the web site / tab in question. I'd like to have a command / hotkey for setting the global zoom that affects every page and tab.

Chormium has this global zoom setting available, but I'd like to have a cVim hotkey for it. See Settings->Advanced->Web Content->Page Zoom.

**Comment by 1995eaton** [comment]
This is currently not accessible via Chrome's current APIs.
