### ISSUE TITLE
Most keys don't work anymore

### ISSUE THREAD

**Issue by ohle** [1995eaton/chromium-vim#432]
Using chromium

    Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)

and cVim `1.2.82`, most of the keys stopped working for me: `j` and `k`, `gg` etc. for scrolling, `f` etc. for hints. I can still switch tabs with `gt` and enter command mode with `:`.

I tried uninstalling and reinstalling `cVim` without any custom settings, and also disabling all other plugins - no luck. Also manually mapping those keys with `:map` doesn't help.

**Comment by etmoore** [comment]
@ohle are you still having these issues?

**Comment by 1995eaton** [comment]
This is likely related to your Chrome version being outdated (current version is 50.0).

**Comment by ohle** [comment]
OK. I'm stuck with 37.0 on this system (Ubuntu precise), so I guess that's my problem, then. It *used* to work fine before, that's why I reported it.
