### ISSUE TITLE
Quickmarks fail in Chromium 50

### ISSUE THREAD

**Issue by terminalmage** [1995eaton/chromium-vim#436]
**cVim version: 1.2.82**

In Chromium 50.0.2661.75, quickmarks no longer work. When trying to launch a quickmark, cVim displays ``Error: quickmark not set``.

After downgrading to Chromium 49.0.2623.112, quickmarks work again.

**Comment by 1995eaton** [comment]
Should be fixed in the latest release

**Comment by terminalmage** [comment]
Confirmed. Took a while for the new release to be pushed to my browser, but it finally did about an hour ago. Thanks!
