### ISSUE TITLE
Quickmarks stopped working since 1.2.82

### ISSUE THREAD

**Issue by nasenatmer** [1995eaton/chromium-vim#439]
Since the last update to 1.2.82, cvim won't open quickmarks any longer, instead giving me `Error: mark not set`.

Did I miss something with the update (the modifications to `:new\winopen` or `:tabnew`)?

To reproduce:

1. Set cvim to use this [minimal cvimrc](https://gist.github.com/nasenatmer/38dab67a5baea05f797e8fdc586d25d5) as example
2. Open new tab, load random website and afterwards type `gob`.
3. I get `Error: mark not set`

This applies to all the other quickmarks I have in my proper cvimrc.

**Comment by 1995eaton** [comment]
This is due to Google removing support for a deprecated JavaScript function. This is fixed in the 1.2.83 version of cVim, which should be available in the he Chrome store now.

**Comment by nasenatmer** [comment]
Great, thanks! And cheers for this amazing add-on and your continued work on it!
