### ISSUE TITLE
Callback is always firing every 10ms on 1.2.83

### ISSUE THREAD

**Issue by rhysd** [1995eaton/chromium-vim#440]
Hi, thank you for great extension 😄 

After v1.2.83,  cVim always consumes CPU at the foreground page.  I tried profiling the page with DevTools' timeline feature, then I found that it fires a callback every 10ms.

<img width="620" alt="2016-04-21 16 42 17" src="https://cloud.githubusercontent.com/assets/823277/14701357/fb646bd8-07df-11e6-980e-cba0aaa64bae.png">

And I found the timer code.

https://github.com/1995eaton/chromium-vim/blob/2f89d1a99cf5b7977d1a59e79ad2012174fdf6c0/content_scripts/command.js#L1034

This is already removed on the HEAD of this repository and it looks to resolve this issue.  So I'll be happy if next version is released as soon as possible :pray:

**Comment by 1995eaton** [comment]
Just published 1.2.84 to the Chrome store. The update should be available in around an hour

**Comment by rhysd** [comment]
Thanks! :+1:
