### ISSUE TITLE
Vim bindings for textarea/input elements

### ISSUE THREAD

**Issue by 1995eaton** [1995eaton/chromium-vim#45]
I've created a [branch](https://github.com/1995eaton/chromium-vim/tree/vim-textarea) that adds very basic support for vim key bindings in normal HTML &lt;textarea&gt; and &lt;input&gt; elements. This is a pretty big change, so it would be great if some of you guys could test it out before I push the commit to master. Thanks!

When textareas/input elements are focused, they enter normal mode. Press 'i' to begin typing and escape to go back to normal mode (press escape/&lt;-[&gt; in normal or visual mode to unfocus the text box.

**Comment by paulhybryant** [comment]
hi,

Is this in the master branch now?

Thank you.

**Comment by 1995eaton** [comment]
I ended up deciding not to merge the branch. I did however implement simple mappable keybindings for input boxes. You can find a description of these in the help page `:help`.
