### ISSUE TITLE
If I don't feed a word to search engine, i will get a blank page

### ISSUE THREAD

**Issue by kosl90** [1995eaton/chromium-vim#451]
If I don't feed a word to search engine, i will get a blank page, not the search engine page. As my test, this just happens for self-defined search engine. Is that technical problem or something else? see my config [cVimConfig](https://gist.github.com/kosl90/3775930ade8eb58bd3d9)

BTW, you may use about:blank for blank page instead of your own blank page. And sometimes, chrome://newtab might be better.

OS: windows7 x64
browser: chrome 51.0.2704.84 m (64-bit)
cVim: 1.2.85

**Comment by 1995eaton** [comment]
It opens a custom blank page because Chrome's newtab page focuses the omnibox on load (which can be annoying). You can disable this by adding `set defaultnewtabpage` to your config.

**Comment by kosl90** [comment]
You might misunderstand what i mean. The point is not you write a blank for some reasons. Let me give you an example.

cVim has predefined search engine like google, so `:tabnew google` goes to https://www.google.com.

Now I defined my own search engine like baidu with `let searchengine baidu = "https://www.baidu.com/s?wd="`.

What I expect is that `:tabnew baidu` goes to https://www.baidu.com, however I get a blank page.

Do you meet this problem?

**Comment by 1995eaton** [comment]
As a side not, I've just added completion result support for baidu. You can now add "baidu" to your completion engine array. For example:

```vim
let completionengines = ['google', 'wikipedia', 'baidu']
```

**Comment by kosl90** [comment]
I'll try it.
