### ISSUE TITLE
wrong selected style for command line

### ISSUE THREAD

**Issue by kosl90** [1995eaton/chromium-vim#452]
![selected-row-problem](https://cloud.githubusercontent.com/assets/1311476/16358042/8a3308fa-3b3a-11e6-8086-5cc54239891f.png)
![selected-row](https://cloud.githubusercontent.com/assets/1311476/16358052/ab800e54-3b3a-11e6-8c78-1c490bfad026.png)

all the even rows get the same problem.

OS: windows7 x64
browser: chrome 51.0.2704.84 m (64-bit)
cVim: 1.2.85

**Comment by 1995eaton** [comment]
Try the reset button in the settings page (make sure you back up your config). This will reset the CSS settings, which might fix this problem.

**Comment by kosl90** [comment]
It doesn't work

**Comment by nesmyslny** [comment]
@1995eaton Thanks, worked for me.
@kosl90 Did you save the settings after reset? For me, this worked: `Reset` -> `Save` -> restart Chromium

**Comment by kosl90** [comment]
@nesmyslny @1995eaton Thanks, worked for me too. I think I forgot to save the settings after reset, I thought reset operations would do this for me.
