### ISSUE TITLE
[localconfig] Add default config location and/or "$HOME" resp. "~" path support

### ISSUE THREAD

**Issue by serialoverflow** [1995eaton/chromium-vim#462]
Hey,

from what i can tell, you currently have to hardcode the exact location to your .cvimrc file if you want to use a local one, e.g.:
```
let configpath = "/home/user/.cvimrc"
set localconfig
```

As someone who synchronizes their dotfiles across many devices this doesn't work because the path is likely to be different on each device. 

My suggestion is to 
a) provide a default .cvimrc location that expands to "~/.cvimrc" or maybe even respect directory standards like [$XDG_CONFIG_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (for linux) etc. But "~/.cvimrc" is a sensible default and something users will expect.

and/or

b) allow "$HOME" or "~" variable for I/O operations like `:source` so that i can implement this behaviour in .cvimrc.

Regards

**Comment by 1995eaton** [comment]
This currently isn't possible due to limitations in Chrome's extension API. The closest you can get to `~` expansion is through the `homedirectory` variable (but it must be set for each device):

```vim
let homedirectory = '/home/jake'
let configpath = '~/.cvimrc'
set localconfig
```
