### ISSUE TITLE
Unable to (re)map Ctrl + N

### ISSUE THREAD

**Issue by lohfu** [1995eaton/chromium-vim#477]
Great plugin,

I have managed to rebind a bunch of default Chrome shortcuts to more vim like behaviour, but Ctrl + N still opens a new window. 

Currently my config is as follows:

```
map <C-d> scrollPageDown
map <C-u> scrollPageUp
map <C-f> scrollFullPageDown
map <C-b> scrollFullPageUp
map <C-n> nextTab
map <C-p> previousTab
```

Is there anyway to make `<C-n>` work as well?

**Comment by ffledgling** [comment]
Coming from Pentadactyl. I'm trying to do the same thing.

```vimrc
map <C-n> nextTab
map <C-p> previousTab
map <M-n> nextTab
map <M-p> previous tab
```

All of the above don't work, and I don't see any errors in the console log. It would be nice to be able to have more vim like behaviour and defaults.

**Comment by 1995eaton** [comment]
Chrome won't let certain keyboard shortcuts like `<C-n>` be bound. However, if you go to the bottom of chrome://extensions and click the "Keyboard shortcuts" button, you can map `<C-n>` to next tab there.
