### ISSUE TITLE
Toggle hover via linkhints.

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [1995eaton/chromium-vim#495]
It could be cool to have a feature to toggle hover on stuff when you just want to see more information instead of following link.

**Comment by hbt** [comment]
`map F createHoverHint
`

**Comment by eyvindbjartiandersen** [comment]
Thank you. Did you just create the function?.

**Comment by hbt** [comment]
view readme 

```
q 	trigger a hover event (mouseover + mouseenter) 	createHoverHint
```
