### ISSUE TITLE
cvim - enabling on the chrome://* pages

### ISSUE THREAD

**Issue by balajijegan** [1995eaton/chromium-vim#496]
hello,  i am following instructions in https://webcache.googleusercontent.com/search?q=cache:YB_zzqHxSboJ:https://www.reddit.com/r/vim/comments/28af5n/cvim_now_with_more_features/+&cd=3&hl=en&ct=clnk&gl=us to enable cvim on "chrome://*/*" pages. 

after cloning the source, and editing the manifest.json, i see the following error when trying to build the extension.

```
$ make
node scripts/create_pages.js
cd ./cvimrc_parser && make
../node_modules/pegjs/bin/pegjs -e RCParser parser.peg && cp parser.js ../content_scripts/cvimrc_parser.js
Can't use the -e/--export-var option with the "commonjs" module format.
make[1]: *** [all] Error 1
make: *** [all] Error 2
```

Here are other possible relevant info:
```
 $ npm version
{ npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.8.0',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }


$ npm list
chromium-vim@ .../chromium-vim
├── highlight.js@9.7.0
├─┬ markdown-it@8.0.0
│ ├─┬ argparse@1.0.9
│ │ └── sprintf-js@1.0.3
│ ├── entities@1.1.1
│ ├── linkify-it@2.0.1
│ ├── mdurl@1.0.1
│ └── uc.micro@1.0.3
└── pegjs@0.10.0

```

Any suggestions on resolving the issue / steps on enabling cvim on chrome:* pages much appreciated. 

Thanks
-balaji

**Comment by mationic** [comment]
nkgm posted a fix: https://github.com/1995eaton/chromium-vim/pull/491

You simply have to add  ```--format globals``` behind the pegjs call in [cvimrc_parser/Makefile](https://github.com/1995eaton/chromium-vim/blob/master/cvimrc_parser/Makefile)

**Comment by balajijegan** [comment]
That helped. Thanks for the tip.

**Comment by balajijegan** [comment]
one other question. is it possible to set the focus on the new tab away from the urlbar so that the cvim shortcuts work? usually i have to press a tab to move the focus away from the url bar before using the vim shortcuts. in the vimperator world, it was (un)elegantly solved by removing / hiding the url bar
