### ISSUE TITLE
Issues with `:viewsource!` and `gs`

### ISSUE THREAD

**Issue by mrzool** [1995eaton/chromium-vim#498]
It's been a while since the `:viewsource!` and `gs` commands have stopped working. I'm running cVim on Chrome 52.0.2743.116 on Mac OS X El Capitan. My cvimrc is pretty much blank.

Anyone with the same issue?

**Comment by h43z** [comment]
Here the same. 
cVim (1.2.85)
Chromium 53.0.2785.143 (Developer Build) built on Debian

**Comment by mrzool** [comment]
Thanks a lot for the fix.
