### ISSUE TITLE
More granular control over keys passed through to webpage

### ISSUE THREAD

**Issue by terminalmage** [1995eaton/chromium-vim#500]
One thing I really miss from Pentadactyl is the ability to set individual keys to pass through to different sites. This allowed me to pass through j, k, etc. on Gmail to navigate through the Gmail web interface. Pentadactyl also has a single-keystroke passthrough (like cVim's `passkeys` only I don't believe it responded to multipliers like cVim's does). The ingenious way it was implemented though, was that keys that were set to be passed through for a given site, when executed after the single-keystroke passthrough, would execute their normal Pentadactyl action. So, say you need to pass through `f` for some reason. You could hit `<C-v> f` and the link hints come up, even though the normal behavior is to pass through that key. It's really the best of both worlds. In addition to all of this, you could hit `<C-z>` and all keys would be passed through until you hit `<C-z>` again (or was it `Esc`? I don't remember.)

This behavior would be fantastic to have in cVim.

**Comment by hbt** [comment]
already implemented in cvim 

command name is passKeys

example:

map v passKeys

then in your browser: vff the first f is skipped, only the second one is executed by cvim

**Comment by terminalmage** [comment]
@hbt thanks, but please read the entire post, where I clearly mention that I already know about ``passKeys``.

**Comment by terminalmage** [comment]
Haven't used Chrome in years and there doesn't seem to be any desire to implement this.
