### ISSUE TITLE
display more than 25 tabs on buffer list 

### ISSUE THREAD

**Issue by zywn** [1995eaton/chromium-vim#506]
When I have more than 25 tabs open at the same time and want to use :buffer to change between them,  only the first 25 tabs is displayed. Using tab alone could only switch between the first 25 items too. I think it'd be nice to be able to add page changing in buffer list.

**Comment by hbt** [comment]
in your config

`let searchlimit = 100
`

**Comment by 1995eaton** [comment]
@hbt is correct
