### ISSUE TITLE
Noremap command does not work

### ISSUE THREAD

**Issue by IniZio** [1995eaton/chromium-vim#507]
I uses jkl; instead of hjkl for my navigation in local nvim. However in cVim it causes error when I put 
```vim
noremap ; l
noremap l k
noremap k j
noremap j h
```
Is noremap not a supported command for cVim?

**Comment by 1995eaton** [comment]
It is not supported as of now, but I plan on adding the feature sometime in the future.

**Comment by IniZio** [comment]
Thanks, hope it will be added
