### ISSUE TITLE
safari plug

### ISSUE THREAD

**Issue by vipheyue** [1995eaton/chromium-vim#512]
can you use this code create safari plug ...... 
i don't know Working time ...
if safari have this greate plug will be perfect

**Comment by 1995eaton** [comment]
I only plan on making extensions for Chrome (which is the browser I use primarily). However, you could try [sVim](https://github.com/flipxfx/sVim), which is based from cVim.

**Comment by malob** [comment]
Any interest in revisiting this now that it's possible to [convert](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) Chrome extensions into Safari 14 extensions?
