### ISSUE TITLE
quick marks in new window not working

### ISSUE THREAD

**Issue by kecmen** [1995eaton/chromium-vim#519]
Hi,

first of all, thanks for this extension, I really like it.

Opening qmarks in new window (gw<*>) is not working. Other possibilities (gn<*> and go<*>) are fine. 
It seems that the 'openLinksWindow' internal function is not really opening anything.

**Comment by 1995eaton** [comment]
It seems to open links fine for me. As an example, I added this line to my config file:

```vim
let qmark a = ['https://google.com', 'https://github.com]
```

What operating system and Chrome version are you using?

**Comment by kecmen** [comment]
Hi,

I'm using Chrome 56.0.2924.87, cVim 1.2.85, tested on Kubuntu 14.04 and Windows 7, none of them is working.
Weird thing I've just noticed is that opening help for cVim (:help) doesn't even contains gw<*> in 'QuickMarks' section. This is however listed on the github page. Calling openQuickMarkWindowed does nothing.

**Comment by kecmen** [comment]
Ok, I've just checked the code directly from git and it seems this has been added in 1.2.86 (together with fixing _**viewsource**_, which is also not working for me).
`git diff c7b3d96024a03a33d7aa185a7f41334b6be46148 HEAD`

But in the official chrome store there is still 1.8.25 version
[https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh]

Is this extension still updated on the store? Or should I clone the sources and build it by myself?

**Comment by 1995eaton** [comment]
Just tested the Chrome Store version (1.2.85) and I can reproduce your issue. I have pushed the current build to the Chrome Store and version 1.2.86 should best publicly available within a few hours. Let me know if you're still having issues after you update and I'll reopen the issue.

**Comment by kecmen** [comment]
Hi,

I can confirm it's working now. Thank you very much .Except of opening marks in new window, the **viewsource** and searchengines with the list of addresses started to work too.
