### ISSUE TITLE
Logout on github when "click" by hints on github logo

### ISSUE THREAD

**Issue by averrin** [1995eaton/chromium-vim#521]
Logout on github when "click" by hints on github logo.
They change design and this bug appears. Very distracting.

**Comment by averrin** [comment]
Its reproduces only when menu id closed.

**Comment by averrin** [comment]
Github said, this error in extension, but i found this:
![image](https://cloud.githubusercontent.com/assets/426007/23342154/5f1e6946-fc66-11e6-907e-1965babc6ca8.png)

**Comment by 1995eaton** [comment]
I've been having this issue as well but GitHub seems to have fixed the issue themselves. Can you confirm that you're no longer having trouble with this?

**Comment by averrin** [comment]
Oh! Nice. Support said its not a bug, but seems like they fix it.
