### ISSUE TITLE
Search engine path replacement not working

### ISSUE THREAD

**Issue by tarao** [1995eaton/chromium-vim#524]
It seems that commit 7031222 broke `%s` handling in search engine paths, e.g., `:tabnew wikipedia test<CR>` opens https://en.wikipedia.org/w/index.php?search=&title=Special:Search not https://en.wikipedia.org/w/index.php?search=test&title=Special:Search .

**Comment by 1995eaton** [comment]
Should be fixed now. Let me know if it's still not working for you.

**Comment by tarao** [comment]
It works for me now. Thanks!
