### ISSUE TITLE
't' for :tabnew starts unfocused

### ISSUE THREAD

**Issue by Tanath** [1995eaton/chromium-vim#527]
Some time in a recent update the behaviour changed. It used to be that I could hit 't' and type to open something in a new tab. Now when I hit 't' I get the dropdown but it's not focused. I have to hit tab, which populates it with whatever's first in line, and I then have to erase it before I can put what I want.

Same is true for 'o' for open, etc.

Currently using cVim 1.2.86 on Chrome version 58.0.3029.19 beta (64-bit), but behaviour hasn't changed over the last few releases.

**Comment by 1995eaton** [comment]
This issue seems to be caused by a Chrome update. I have been experiencing this issue under Chrome Beta in OS X (only after updating Chrome), but not under Chromium in Linux. 6c31f2c should fix this issue, but let me know if the issue still persists after the latest commit.

**Comment by Tanath** [comment]
Can you tell me when the fixed version will be released?

**Comment by 1995eaton** [comment]
Just pushed the latest release to the Chrome Store. The newest version should be available in about an hour.
