### ISSUE TITLE
command ":buffer " can not work in Version 1.2.87

### ISSUE THREAD

**Issue by hankeryo134** [1995eaton/chromium-vim#529]
Hello,I am a vimer,using the productive tools in China.
It's troubling me that the command ":buffer <tab number> "can jump to the selected tab only only in lastest version but older.
so I must downgrade the Cvim to Version 1.2.86 everytime for autoupdating.
Improvement or some tips  will be appreciated.
Thanks.
Windows 7 x64
Google Chrome 57.0.2987.110

**Comment by x-ji** [comment]
It is caused by the commit https://github.com/1995eaton/chromium-vim/commit/0e249e0b1b96f43ee06803bc9c23e01114374990
