### ISSUE TITLE
Broken in new vivaldi builds

### ISSUE THREAD

**Issue by averrin** [1995eaton/chromium-vim#534]
Overlay exists, block controls, but invisible.
Both in windows and linux.
Totally unusable=(

**Comment by averrin** [comment]
It still works in 1.8.* but not in 1.9.*

**Comment by leliamesteban** [comment]
It works for me.
`vivaldi-stable --version` shows 
'Vivaldi 1.9.818.50'
I don't know what you mean about overlay or block controls, but it's definitely not unusable

**Comment by averrin** [comment]
Yeah, it was fixed by vivaldi itself right after release
