### ISSUE TITLE
open highlighted text in tab and mouse buffer

### ISSUE THREAD

**Issue by AlexYeCu** [1995eaton/chromium-vim#546]
Looks like function (or ability) «open highlighted text in current/new tab» (p or P hotkey) does not work with mouse buffer (text which selected moves to a special buffer and then can be pasted with midle nouse button). Looks like this function works only with copied with ctrl+c texts.

**Comment by 1995eaton** [comment]
This is not currently possible to implement because Chrome only allows JavaScript to access the primary clipboard.

**Comment by AlexYeCu** [comment]
Well, this functionality may be realesed thorough calling a calling of external shell script or through reading a file. For example, user presses a hotkey, and gviv reads a file with mouse selection. Or calls user's script which returns us the information.
