### ISSUE TITLE
Possible to unmap middle mouse click?

### ISSUE THREAD

**Issue by SohMahmood** [1995eaton/chromium-vim#549]
Hi i know this extension is supposed to remove the need for a mouse but sometimes your laid back in your chair and you just wanna move using the mouse.

Problem is that i use the middle click mouse button A LOT to scroll but i think cvim maps middle click to paste so the auto scroll is blocked. Is there a work around this issue?

**Comment by cedric-sun** [comment]
cVim doesn't map the middle click of mouse to paste. This is [a common feature](https://help.ubuntu.com/stable/ubuntu-help/mouse-middleclick.html) on many desktop environments of *nix OS.

Maybe you can find some instructions on how to disable this feature in the manual of your desktop environment.
