### ISSUE TITLE
map :bookmarks with a space

### ISSUE THREAD

**Issue by wocala** [1995eaton/chromium-vim#550]
if not map :bookmarks, when I click b, it will show a command with :bookmarks and automatically with a sapce, which means I can directly type and get the autocompletion.
But after I map, like "map b :bookmarks!", it won't have the last space, which means I have to type a space every time before I can type what I want to search.
Can you please fix this? Thanks~

**Comment by lehmacdj** [comment]
Just use the mapping `:map b :bookmarks!<Space>` to automatically append the space.
