### ISSUE TITLE
Could not unzip extension

### ISSUE THREAD

**Issue by mruwek** [1995eaton/chromium-vim#554]
Such error is showed when I try to install cVim via Chrome Web Store. Installing via "devloper mode" works however.

Windows 7 64-bit, Chrome version:  59.0.3071.115 (Official Build)

**Comment by 1995eaton** [comment]
Strange, cVim's zip file must have been corrupted when I uploaded an updated version to the Chrome store.

I've uploaded another version to the store (1.2.92) and the issue appears to be fixed on my end.
Let me know if you're able to install the new one.

**Comment by mruwek** [comment]
Yep, installs now without an issue. Thanks
