### ISSUE TITLE
can `escape` exit from address bar as well?

### ISSUE THREAD

**Issue by timepp** [1995eaton/chromium-vim#560]
when I happen to hit "alt+d" address bar get focused and there is no simple way to get address bar un-focused.

Can `escape` key help here, just like it can de-focus any edit box inside webpage?

**Comment by timepp** [comment]
FYI: VimFx works as expected. When you press "ESC" with focused address bar then the address bar will lose the focus.

**Comment by TheZoq2** [comment]
Without knowing much about the subject i believe the answer is that web-extensions don't have access to the browser UI and as such, cant manipulate it. VimFX can do it because it is a legacy extension

**Comment by lydell** [comment]
TheZoq2 is correct.

**Comment by jaimehrubiks** [comment]
In case someone needs a quick tip on this, you can hit TAB and then you may get to normal mode.

**Comment by 1995eaton** [comment]
@TheZoq2 and @lydell are right, there is no way to do this with Chrome's current extension API
