### ISSUE TITLE
Feature enhancement-- Make switching tab more efficiency

### ISSUE THREAD

**Issue by Celthi** [1995eaton/chromium-vim#565]
I have scan through how to navigate among tabs. Here is what I personally think. 

When navigate among tabs, `gt` or something are not as efficiency as using a mouse to click the tab because with mouse you can quickly click the tab you want to navigate.

Using gt or `crtl+number` could not have the feeling as just click the tab name.

With `gt`, sometime you need more than one gt. With `ctrl+number`, you should know the number of the tab you want to navigate to, in which counting is the approach but not a satisfied way to do it.

A way to get a better feeling about navigate to the exact tab, I think maybe adding a the number display in the  tabs could be a method. With the number, I know the exact tab to go to, so I just `ctrl + the number`.

**Comment by stekern** [comment]
There already exists a flag for displaying the tab indices. Just add `set showtabindices` to your .cvimrc :-)

**Comment by Celthi** [comment]
bravo ^-^
