### ISSUE TITLE
Is it possible to use multiple modifiers in a map?

### ISSUE THREAD

**Issue by TheIronMarx** [1995eaton/chromium-vim#569]
I want a combination of modifiers plus a key to do an action.

I've tried the following (and similar) without success.
```map <C-M-A-i> nextTab```

Am I only restricted to a single modifier + a key to perform an action?

**Comment by 1995eaton** [comment]
Should be fixed now. Let me know if it's working for you!

**Comment by TheIronMarx** [comment]
Regrettably, it isn't. I wrote a lousy ticket. I should have started with "I'm on OSX." Apple has been known to do some funky things with exposing modifiers.
