### ISSUE TITLE
Vulnerability: websites can control your browser by generating synthetic DOM events.

### ISSUE THREAD

**Issue by eejdoowad** [1995eaton/chromium-vim#572]
For example, try entering the following in the console. The page will scroll down.

document.dispatchEvent(new KeyboardEvent('keydown', { key: 'd', code: 'KeyD' }))

The fix is to check the isTrusted attribute on Events.

**Comment by 1995eaton** [comment]
Wow, Chrome finally added the support to dispatch keyboard events via JavaScript. I remember this not working before.

Anyways, thanks for bringing this issue to my attention. It should be fixed now.
