### ISSUE TITLE
`createHoverHint` and `createUnhoverHint` break. `P` (openPasteTab) fails to handle multiple lines URLs without protocol.

### ISSUE THREAD

**Issue by cedric-sun** [1995eaton/chromium-vim#573]
Neither `q` nor `Q` works. `zr` fails to restart chrome, too.

If there are multiple lines in the clipboard, where each line is a URL starting without the protocol prefix (`http://` or `https://` or some other protocols supported by Chrome), triggering `P` (openPasteTab) will concatenate all the lines into one and try to open it in new tab, which either becomes a keyword search or a 404 path on the first domain.

Try test the following URLs. I randomly pick them from SO.
```
stackoverflow.com/questions/36005436/the-request-was-rejected-because-no-multipart-boundary-was-found-in-springboot
stackoverflow.com/questions/45889791/union-typing-in-z3
stackoverflow.com/questions/387086/crystal-reports-11-how-do-you-debug-a-crystal-report
stackoverflow.com/questions/45932373/python-how-to-access-two-dimensional-list-that-is-a-value-in-a-dictionary
stackoverflow.com/questions/45932402/return-paypal-email-address-from-paypalmerchantsdk
```

**Comment by 1995eaton** [comment]
2ed2c90 and c88b298 should fix these issues. I was however unable to reproduce the hover hint problems you are having. Create a new issue if you are still having this problem.
