### ISSUE TITLE
GitHub user profile icon link is not found when you click `f`

### ISSUE THREAD

**Issue by karlfloersch** [1995eaton/chromium-vim#585]
It seems that the user icon in the top right hand side of GitHub does not get selected when you click `f` using cVim.

![this](https://user-images.githubusercontent.com/706123/32028953-4484511a-b9a6-11e7-8b17-0cb925b05e0f.png)

_Sorry if this has already been reported. I searched for `GitHub` in the issues but didn't see anything relevant_

### Thank you so much for this great extension!

**Comment by 1995eaton** [comment]
Seems to work for me on the latest version of cVim.

![asdf](https://user-images.githubusercontent.com/5422476/33869154-55e0d952-ded5-11e7-9a41-ad8d49846350.png)
