### ISSUE TITLE
Map openQuickMarkTabbed

### ISSUE THREAD

**Issue by Druidefix** [1995eaton/chromium-vim#589]
Hello,

for a specific sites it is easier for me to `unmapAll` and then map the keys I like for this page to work. I manage to restore nearly all behavior, but I do not know how to restore the quick marks settings.

How do I map `openQuickMarkTabbed` again to `gn<*>`?

**Comment by 1995eaton** [comment]
You can use `map gn* openQuickMarkTabbed`
