### ISSUE TITLE
How to Save data to file ?

### ISSUE THREAD

**Issue by jkeks** [1995eaton/chromium-vim#593]
vimperator can normally save to file by code:

`map <silent> w :js (function(){var f = new io.File('~/testfile'); f.write(window.content.location.href+'-=736872648273628=-'+window.content.document.documentElement.innerHTML); delete f;})()<cr>:echo"Copied"<cr>`

can't do it with cVim .. how ?

**Comment by 1995eaton** [comment]
Chrome's extension API does not allow this (and as far as I'm aware vimperator on newer versions of Firefox cannot).
