### ISSUE TITLE
What is the HUD?

### ISSUE THREAD

**Issue by nedludd** [1995eaton/chromium-vim#599]
There is no explanation of what the HUD is, except in the example .cvimrc, which maps a key to turn it off.

If I do `:set hud` nothing happens.  If I do `:set nohud` nothing happens.

Some insight would be helpful.

**Comment by LNQ** [comment]
I believe the hud is the info box, that appears in the top right corner. For example if you start the link hints with f, in the top right corner a element appears wich says "Follow link".
thats all.

**Comment by nedludd** [comment]
Ah, got it.  Thanks.
