### ISSUE TITLE
Link hint site filters should be extendable as settings

### ISSUE THREAD

**Issue by jmbeach** [1995eaton/chromium-vim#600]
The file /content_scripts/hints.js has the property `Hints.siteFilters`. This would be great to be able to extend in your own custom settings, but I don't see a way to do that without editing the extension.

**Comment by 1995eaton** [comment]
You can add a global script that can extend the site filters

```javascript
-> {{
  const extraFilters = {
      '*://*': {
          reject: ['a'],
          accept: [],
      }
  };

  Object.getOwnPropertyNames(extraFilters).forEach(pattern => {
      Hints.siteFilters[pattern] = extraFilters[pattern];
  });
}}
```
This would reject all link tabs on all pages, but you can modify the `extraFilters` variable to your liking.

**Comment by jmbeach** [comment]
I appreciate it
