### ISSUE TITLE
you can map 'close tab' - but what's it for 'open new tab'? i dont see it on the 'keybindings' list

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [1995eaton/chromium-vim#602]
you can map 'close tab' - but what's it for 'open new tab'? i dont see it on the 'keybindings' list

**Comment by 1995eaton** [comment]
`map t :tabnew<CR>` will open a blank page if you press `t`. Alternatively, you can open Chrome's new tab page with `map t :tabnew chrome://newtab<CR>`
