### ISSUE TITLE
Removes Console Output

### ISSUE THREAD

**Issue by haffla** [1995eaton/chromium-vim#623]
Hey,

I am not sure since when this is happening but I am quite sure that I haven't changed any settings in my Chrome Dev Tools.
The first few lines of console output disappear ~ a second after page load. When I enable "preserve log" I see

`Navigated to chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/cmdline_frame.html`

Any idea what the cause for this could be?

Thank you!

**Comment by ohjames** [comment]
Same thing hit me. Cannot do web development work with this extension like this, it must be calling `console.clear` somewhere which is so unhelpful.

**Comment by ohjames** [comment]
Same issue is affecting vimium, more info here: https://github.com/philc/vimium/issues/2907

**Comment by eyaleizenberg** [comment]
Already fixed on vimium.... :(

**Comment by ohjames** [comment]
Yep, and vimium also supports Firefox.

**Comment by bryanparadis** [comment]
The iframe is what breaks it. I commented out some lines, as shown below and it is working so far as usual.

content_scripts/command.js
{code}
1026 Command.onDOMLoad = function() {
1027   this.onDOMLoadAll();
1028   if (window.self === window.top) {
1029     // Command.frame = document.createElement('iframe');
1030     // Command.frame.src = chrome.runtime.getURL('cmdline_frame.html');
1031     // Command.frame.id = 'cVim-command-frame';
1032     // document.lastElementChild.appendChild(Command.frame);
1033   }
1034 };
{code}
