### ISSUE TITLE
Is there a passkeys feature like pentadactyl?

### ISSUE THREAD

**Issue by ghost** [1995eaton/chromium-vim#65]
The ability to send some keys through to the web app while preserving others for cVim would be hugely helpful. Enable/disable cVim entirely per page/site is too limiting for so many web apps with keyboard shortcuts. This feature (and #47) are in fact the reasons I switched away from Chrome to FF + pentadactyl. Please let me know if this is already present in cVim!

**Comment by koro-xx** [comment]
Is it possible to whitelist only certain keys? For example, can I blacklist "*://mail.google.com/*" but then whitelist "*://mail.google.com/* J K x f"? I've tried
let blacklists = ["*://mail.google.com/*", "@*://mail.google.com/* J K x f"]
but this seems to allow every keyboard shortcut and not just J K x f.
