### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by thynctank** [1995eaton/chromium-vim#680]
I just changed machines at work, and suddenly I'm getting errors in console, regardless of page visited or anything else I have noticed, and I narrowed down that it's coming from cVim. Unfortunately, the console error will not jump to the source, instead insisting that the error came from the root page, loading the HTML of the page visited in the source browser instead.

It doesn't appear to cause any usability errors, but as we're in the middle of a release I thought it was a newly-introduced bug in our own code when I saw it. I've never seen it before and hadn't seen this bug anywhere else. A quick googling brought up https://github.com/mozilla/webextension-polyfill/issues/130 and lydell's associated bug reproduction repo on GitHub.

I'm more than happy to contribute a few minutes here and there to cVim. But I'm new to the project and have barely touched extension code before at all. If someone can point me in the right direction I'll happily fork/correct/make PR and continue running my locally-built extension until the next official release gets picked up with a fix. I failed to locate any specific strings relating to this bug, but wondered if it might be coming from messenger.js...

Thanks!

**Comment by thynctank** [comment]
Hey, @tommai78101. 

I haven't had sufficient time/energy/attention span to look into this further yet. Of the 20+ extensions I use, cVim is the only one suffering the issue right now. I am inclined to believe it's something in more recent builds of Chrome itself because before my from-scratch installation on the new machine I never saw this.

I would suggest downgrading Chrome and disabling auto-update, or running a more recent Canary or Chrome build - if they've managed to patch it already - if this is significantly affecting you. Eventually, newer Chrome builds should push out to everyone and the issue will evaporate.

**Comment by hotleave** [comment]
may be this page will give you some help:

https://support.google.com/chrome/thread/2047906?hl=en

**Comment by wtho** [comment]
Yeah it is definitely used [several times](https://github.com/1995eaton/chromium-vim/search?q=sendMessage&unscoped_q=sendMessage) in cVim.

**Comment by grandsilence** [comment]
Issue still unsolved :( Cent Browser latest.

**Comment by radheshyamkori** [comment]
Following solved the above error for me:
In chrome,
i) Go to settings
ii) Click on Extensions
iii) Check for "Meddle Monkey" extension. if it is on turn off and remove this extension
iv) Refresh your chrome browser
v) Inspect element and check for the Error "The message port closed before a response was received". 
vi) You will find that now the error is not displayed, it is resolved

Thanks

**Comment by grandsilence** [comment]
Any news?
