### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by dcchambers** [1995eaton/chromium-vim#723]
Has this project effectively been abandoned?

No source code updates since November 2017. More bugs are starting to crop up and issues and PRs on GitHub have been open for years with no answers.

**Comment by Legend94rz** [comment]
I have found some substitute plugins: "Vimium" and "Vimium C".
You could get them by searching "Vimium" in the Chrome store.

**Comment by schmitmd** [comment]
Without wanting to offend anyone, I think it's probably safe to say "yes" here.  #716 and #721 are the same issue, have two different pull requests (#724 , #719 ), and the broken functionality is **link hinting**?  At least for my own use case, that's _really_ basic on the necessary/important features of this extension...
@1995eaton , can you weigh in here?

**Comment by jakem72360** [comment]
@dcchambers @schmitmd I emailed the dev in September asking about my PR #713. I still haven't heard back, so I'd say yes. The extension errors out now on when I click enable after a recent Chromium update.

I'd be interested in submitting PR's to a fork, but don't have the time to maintain one myself. Any takers?

**Comment by dcchambers** [comment]
@schmitmd yeah...I came here looking for a fix after my last chrome update broke that link hinting functionality - which is ~50% of my usage with cVim. Sad to see this project die out - as I like it quite a bit more than the other chrome vim-bindings extensions.

@jakem72360 Thought about it, I use the exention...extensively (haha) and I probably do have the bandwidth to maintain a fork, but I'm not a JS developer so I'd feel a little bit like a fish-out-of-water trying to get a hold of things for a while. 🤔

**Comment by ShawnConn** [comment]
Is there a Chrome Dev extension policy against forking a project then submitting builds to the Chrome Web Store? I have a Chrome Dev account to host a build, but I'm guessing copying/modding extensions might look suspicious and trigger some automated systems looking for nefarious extension spoofing. 

Ideally, someone would get a hold of @1995eaton to see if he could add a maintainer to GH & the Chrome Web Store project.

**Comment by dcchambers** [comment]
@ShawnConn Not to my knowledge - AFAIK there are forks of projects in the Chrome web store already. e.g. Adblock stuff. This project is MIT licensed so there's no legal issue with creating a fork.

I agree though - that's the ideal situation.

**Comment by DarkWiiPlayer** [comment]
@ShawnConn In the worst case, couldn't the fork simply be rebranded? This would also come with the benefit of indicating to the users that it's a fork of this project.

@dcchambers Can relate to that; I also use cvim a lot but am not a JS dev so wouldn't feel comfortable taking over the project.

Lately I've noticed more and more things slowly breaking and it'd be a shame if the extension just slowly died, so I really hope someone with some JS forks it.

**Comment by dcchambers** [comment]
@DarkWiiPlayer that's not a bad idea to get a note to @1995eaton. I wonder if he would be open to adding (a) maintainer(s)...or at the very least, merging a few of these changes necessary to fix critical bugs.

**Comment by dcchambers** [comment]
Going to read through the code this weekend to see if forking this is something I'd be capable of taking on. A quick glance shows some pretty sparsely documented code. But if there are any *experienced* JS devs that use this tool and want to keep it alive - **please speak up and let's set up a maintained fork!**

**Comment by cabaalexander** [comment]
@dcchambers I work on JS, if you're going to re-upload this to the store and need some help for maintaing it I'm in. ( :

**Comment by akai1831** [comment]
Guys, please have a look on [SurfingKeys](https://github.com/brookhong/Surfingkeys) as alternative, it is actively maintained by Developer.

Kind regards,
Red

**Comment by jmlucjav** [comment]
> Guys, please have a look on [SurfingKeys](https://github.com/brookhong/Surfingkeys) as alternative, it is actively maintained by Developer.
> 
> Kind regards,
> Red

yeah, I reviewed the current status, and picked https://github.com/brookhong/Surfingkeys as well. Seems to have good momentum (vimium looks fine as well). Although we have to praise @dcchambers for taking initiative, no matter what the outcome

**Comment by CodyReichert** [comment]
@dcchambers - I'm a JS dev and would be happy to help review bug fixes and maintain a fork. My time _right now_ is limited so I may not be able to work on adding new features; but cVim is a core part of my workflow and can absolutely help verify PRs and explain the code to anyone looking to work on it.

Forking this code and releasing a new Chrome extension will not be problematic (as you mentioned, it's MIT). The name just needs to be changed (`cVim2`, `vChrome`, etc, would all be acceptable).

Anyway, ping me on this issue or at the email in my profile if I can help and thanks for initiative.

**Comment by dcchambers** [comment]
Hey folks, I've made a fork here: https://github.com/dcchambers/vb4c and I am in the final stages of getting the fixed version deployed to the chrome web store. I will update once that is done.

New project is called **vb4c** - vim bindings for chrome.

Also I am converting that repository to a stand-alone repo rather than a forked repo as its easier for tracking new release verisons and more, since it appears those changes will never get pushed back into this upstream project.

---
Status:
- [x] Fork and merge in the fix for hinting functionality. (Included the fix (#719) from @antonioyon. Thanks!)
- [x] Update docs, README, and html pages to reflect the change to the new fork.
- [ ] [**In Progress**] Release patched version to Chrome Web store.
- [ ] Determine the future of the project
  - This fix should buy us a little more time while we figure out if this is something worth maintaining, or if migrating to a different tool is best.
  - There are a lot of good options today that weren't available when cVim was first released.
  - If we choose to maintain this project, which I am interested in doing, I will be looking for some co-maintainers that have better javasript skills than me. 😄 Look for active discussion in the [vb4c repo](https://github.com/dcchambers/vb4c)

**Comment by dcchambers** [comment]
Hi all! Quick update - I have submitted an initial version of vb4c to the Chrome web store. It is currently pending review from Google. I will update once it has been published! Thanks for the patience.

**Comment by imcoddy** [comment]
nice work. looking forward to see it on chrome web store

**Comment by serpro69** [comment]
Great job @dcchambers and thanks for trying to keep the project alive!

**Comment by dosentmatter** [comment]
Do you guys know what happened to the current extension on the Chrome web store? https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh is a dead link now. Did the 1995eaton remove it?

**Comment by j4hangir** [comment]
> Do you guys know what happened to the current extension on the Chrome web store? https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh is a dead link now. Did the 1995eaton remove it?

Not that important as the current one is mainly broken.

**Comment by erichamers** [comment]
@dcchambers Did you publish it on the store? I can't find it.

**Comment by dcchambers** [comment]
Since the original https://github.com/1995eaton/chromium-vim project has been updated to fix the "hints" feature, and I have not had the time to be an active maintainer of this project, I will be placing this repo into archived status. For more details, please see [this comment](https://github.com/dcchambers/vb4c/issues/23#issuecomment-810694017).
