### ISSUE TITLE
Add option to not focuing on any input box

### ISSUE THREAD

**Issue by j5shi** [1995eaton/chromium-vim#77]
It would be very usful to add an option allowing users to control if chrome will focus on any input box or not by default when a page is loaded, since in many cases one doesn't need to key in any character on a page, just browsing. So, if you stroke a key, for example, 'f', you will find actually you are keying an 'f' to some input box if the default focus is on some input box, then you have to stroke tab to move the focus to another control and then ... which is quite annoying.

Just like the page of www.google.com, when loaded, you stroke 'f', you are keying 'f' in the search bar, which is not desired.

**Comment by paroxyzm** [comment]
This option does not seem to work...
My config is this:


map <C-h> previousTab
map <C-l> nextTab
set nohud
set nosmoothscroll

set noautofocus " The opposite of autofocus; this setting stops
                " sites from focusing on an input box when they load

**Comment by paroxyzm** [comment]
map C-h previousTab
map C-l nextTab
set nohud
set nosmoothscroll

set noautofocus " The opposite of autofocus; this setting stops
                " sites from focusing on an input box when they load
