### ISSUE TITLE
Web page can access cVim command area

### ISSUE THREAD

**Issue by itchyny** [1995eaton/chromium-vim#85]
The following test page disables the user to use cVim command area normally.
```html
<script>
  window.addEventListener('keydown', function (e) {
    if (e.keyCode == 13)
      document.querySelector("input#cVim-command-bar-input").value = "open https://www.google.com/search?site=imghp&tbm=isch&source=hp&q=apple";
  }, true);
</script>
<p>You cannot use cVim, hehehe... and you must like an apple...</p>
```
This example just opens google image, but they can lead us to a malicious web page.

**Comment by itchyny** [comment]
You will not fix this serious security problem?

**Comment by 1995eaton** [comment]
I plan on fixing it, but it might take a while. I haven't had a lot of time to work on cVim recently (full time college student). This will be a pretty big change, and I only want to start working on it when I can focus my time on the issue full-time. All of the issues I haven't closed I plan on addressing when I can.

**Comment by itchyny** [comment]
OK. Relieved to see that. Hope it fixed.

**Comment by 1995eaton** [comment]
Finally got around to implementing this. As far as I can tell, everything works as before, but with added the added security of DOM isolation. As soon as I get some feedback on how this patch is working, I'll go ahead and close this issue.

**Comment by itchyny** [comment]
I am very sorry but I do not use this extension since I use my own one. Please feel free to close this issue if you think it working well.

**Comment by HerringtonDarkholme** [comment]
LGTM :)
